from setuptools import setup, find_packages
import re
import os

__version__ = re.findall(
    r"""__version__ = ["']+([0-9\.]*)["']+""",
    open("adflow/__init__.py").read(),
)[0]

this_directory = os.path.abspath(os.path.dirname(__file__))
with open(os.path.join(this_directory, "README.md"), encoding="utf-8") as f:
    long_description = f.read()

with open("doc/requirements.txt") as f:
    docs_require = f.read().splitlines()


def _writeGitInfo():
    """Stamp the git revision being installed into the package itself.

    Runs load ADflow from site-packages, not from ./adflow, so the repo's
    current HEAD is NOT necessarily the source that is executing -- that is
    exactly the stale-install trap this is meant to expose. Recording the
    revision here, at ``pip install`` time, ties the stamp to the thing that
    actually gets imported. Degrades to "unknown" outside a git checkout
    (e.g. a tree copied to an HPC without .git).
    """
    import subprocess
    import datetime

    def git(*args, default="unknown"):
        try:
            out = subprocess.check_output(
                ["git", *args], cwd=this_directory, stderr=subprocess.DEVNULL
            )
        except Exception:
            return default
        return out.decode(errors="replace").strip()

    info = {
        "GIT_HASH": git("rev-parse", "--short", "HEAD"),
        "GIT_HASH_FULL": git("rev-parse", "HEAD"),
        "GIT_BRANCH": git("rev-parse", "--abbrev-ref", "HEAD"),
        "GIT_DESCRIBE": git("describe", "--tags", "--always", "--dirty"),
        # Uncommitted changes at install time: the stamp alone would not
        # identify the source in that case, so flag it loudly.
        "GIT_DIRTY": bool(git("status", "--porcelain", default="")),
        "GIT_REPO_PATH": this_directory,
        "INSTALL_TIME": datetime.datetime.now().strftime("%Y-%m-%d %H:%M:%S"),
    }

    target = os.path.join(this_directory, "adflow", "gitInfo.py")
    with open(target, "w") as fh:
        fh.write('"""AUTO-GENERATED by setup.py at install time. Do not edit, do not commit."""\n\n')
        for key, val in info.items():
            fh.write("%s = %r\n" % (key, val))


_writeGitInfo()

setup(
    name="adflow",
    version=__version__,
    description="ADflow is a multi-block structured flow solver developed by the MDO Lab at the University of Michigan",
    long_description=long_description,
    long_description_content_type="text/markdown",
    keywords="RANS adjoint fast optimization",
    author="",
    author_email="",
    url="https://github.com/mdolab/adflow",
    license="LGPL version 2.1",
    packages=find_packages(include=["adflow*"]),
    package_data={"adflow": ["*.so"]},
    install_requires=[
        "numpy>=1.16,!=1.24,!=1.24.1,!=1.24.2",
        "mdolab-baseclasses>=1.4",
        "mpi4py>=3.0",
        "scipy",
    ],
    extras_require={
        "docs": docs_require,
        "testing": ["parameterized", "testflo", "idwarp", "pygeo", "pyspline"],
        "mphys": ["openmdao", "mphys", "idwarp"],
        "complex": ["complexify"],
    },
    classifiers=["Operating System :: Linux", "Programming Language :: Python, Fortran"],
)
