# built-ins
import unittest
import numpy
import os
import copy
from collections import defaultdict
from parameterized import parameterized_class
from mpi4py import MPI

# MACH classes
from pygeo import DVGeometry
from idwarp import USMesh

from adflow import ADFLOW
from adflow import ADFLOW_C
from idwarp import USMesh_C

import reg_test_utils as utils
from reg_default_options import adflowDefOpts, IDWarpDefOpts
import reg_test_classes

from baseclasses import AeroProblem

baseDir = os.path.dirname(os.path.abspath(__file__))

"""
AR5 plain-wing case, PLAIN SA (not SA-GR). Purpose: validate the
derivative-verification harness (FD/dot-product/CS ladder,
docs/ADFLOW_BASE/debugging_derivatives.md) on the AR5 mesh + AR5 FFD
independently of the SA-GR model -- isolates "is a discrepancy a mesh/FFD
problem" from "is it a SA-GR-specific bug". Mirrors test_adjoint_sagr.py's
structure (local-shape-only DVGeo, no hardcoded ref-axis geometry) but with
turbulencemodel=SA and the plain-SA AR5 restart (ar5_plain_wing_sa_dp.cgns,
generated by gen_ar5_sa_restart.py).
"""

ar5GridFile = os.path.join(baseDir, "../../input_files/ar5_plain_wing_vol_L3.cgns")
ar5SARestartFile = os.path.join(baseDir, "../../input_files/ar5_plain_wing_sa_dp.cgns")
ar5FFDFile = os.path.join(baseDir, "../../input_files/ar5_plain_wing_ffd_L3.xyz")

ap_ar5_sa = AeroProblem(
    name="ar5_plain_wing_sa",
    alpha=0.0,
    beta=0.0,
    mach=0.2,
    P=101325.0,
    T=288.15,
    areaRef=0.1,
    chordRef=1.0,
    xRef=0.0,
    yRef=0.0,
    zRef=0.0,
    evalFuncs=["cl", "cd", "cmz", "drag"],
)

ar5SAOptions = {
    "gridfile": ar5GridFile,
    "restartfile": ar5SARestartFile,
    "equationtype": "RANS",
    "turbulencemodel": "SA",
    "liftindex": 3,
    "smoother": "DADI",
    "mgcycle": "sg",
    "useanksolver": True,
    "usenksolver": True,
    "ankswitchtol": 1.0,
    "ankcoupledswitchtol": 1e-5,
    "anksecondordswitchtol": 1e-6,
    "ankunsteadylstol": 2.0,
    "ankphysicallstol": 0.8,
    "ankadpc": True,
    "nkadpc": True,
    "nkswitchtol": 1e-5,
    "nksubspacesize": 300,
    "ankcfllimit": 1e6,
    "ankchartimesteptype": "VLR",
    "solutionprecision": "double",
    # explicit, generous budget: the CS class's resetFlow+cold-resolve needs
    # to fully reconverge each perturbed call (the default nCycles cut it
    # off around Iter Tot ~1000, short of the ~1387 the restart itself
    # needed to reach machine precision -- real mode uses getResidual, not
    # a full solve, so it's unaffected by this)
    "ncycles": 5000,
    "l2convergence": 1e-14,
    "adjointl2convergence": 1e-14,
    # AR5 (195k volume nodes) is much bigger than the tutorial wing this
    # options block was otherwise modeled on -- default adjointmaxiter=500
    # cut the KSP off mid-convergence (residual smoothly falling, 54 ->
    # 6.5e-11, not stalled) before reaching adjointl2convergence. Raised,
    # not loosened -- the target tolerance is unchanged.
    "adjointmaxiter": 2000,
    "turbintensityinf": 0.0025,
    "frozenturbulence": False,
}


def getDVGeo(ffdFile, isComplex=False):
    # local shape DVs only -- no hardcoded ref-axis geometry (AR5's span/
    # chord extents aren't known/matched here), same rationale as
    # test_adjoint_sagr.py's getDVGeo
    DVGeo = DVGeometry(ffdFile, isComplex=isComplex)
    DVGeo.addLocalDV("shape", lower=-0.05, upper=0.05, axis="y", scale=10.0)
    return DVGeo


test_params = [
    {
        "name": "ar5_sa",
        "options": copy.deepcopy(ar5SAOptions),
        "ref_file": "adjoint_ar5_sa.json",
        "aero_prob": copy.deepcopy(ap_ar5_sa),
        "evalFuncs": ["cl", "cd", "cmz", "drag"],
        "N_PROCS": 2,
    },
]


@parameterized_class(test_params)
class TestAdjointAR5SA(reg_test_classes.RegTest):
    """Real-mode: residuals + adjoint totals (mirrors TestAdjoint/TestAdjointSAGR)."""

    N_PROCS = 2

    def setUp(self):
        if not hasattr(self, "name"):
            return
        super().setUp()

        options = copy.copy(adflowDefOpts)
        options["outputdirectory"] = os.path.join(baseDir, options["outputdirectory"])
        options.update(self.options)

        self.ffdFile = ar5FFDFile
        mesh_options = copy.copy(IDWarpDefOpts)
        mesh_options.update({"gridFile": options["gridFile"]})

        self.ap = copy.deepcopy(self.aero_prob)
        self.ap.evalFuncs = self.evalFuncs
        for dv in ["alpha", "mach", "P", "T"]:
            self.ap.addDV(dv)

        self.CFDSolver = ADFLOW(options=options, debug=True)
        self.CFDSolver.setMesh(USMesh(options=mesh_options))
        self.CFDSolver.setDVGeo(getDVGeo(self.ffdFile, isComplex=False), pointSetKwargs={"embTol": 1e-12, "eps": 1e-14})

        self.CFDSolver.getResidual(self.ap)

    def test_residuals(self):
        utils.assert_residuals_allclose(self.handler, self.CFDSolver, self.ap, tol=1e-10)

    def test_adjoint(self):
        utils.assert_adjoint_sens_allclose(self.handler, self.CFDSolver, self.ap, tol=1e-10)
        self.assert_adjoint_failure()

    def test_adjoint2(self):
        utils.assert_adjoint2_sens_allclose(self.handler, self.CFDSolver, self.ap, tol=1e-10)
        self.assert_adjoint_failure()

    def test_adjoint_states(self):
        utils.assert_adjoint_states_allclose(self.handler, self.CFDSolver, self.ap, tol=1e-10)
        self.assert_adjoint_failure()


@parameterized_class(test_params)
class TestCmplxStepAR5SA(reg_test_classes.CmplxRegTest):
    """Complex-mode: CS vs adjoint totals (mirrors TestCmplxStep/TestCmplxStepSAGR)."""

    N_PROCS = 2
    h = 1e-40

    def setUp(self):
        if not hasattr(self, "name"):
            return
        super().setUp()

        options = copy.copy(adflowDefOpts)
        options["outputdirectory"] = os.path.join(baseDir, options["outputdirectory"])
        options.update(self.options)
        # ANKADPC/NKADPC use Tapenade forward (_d) routines to assemble the
        # PC Jacobian -- real-mode only, not complexified. The complex build
        # aborts ("Forward AD routines are not complexified") if they're on.
        # Not needed here anyway: the CS run only takes an infinitesimal
        # (1e-40j) step off an already-converged restart, not a cold start.
        options["ankadpc"] = False
        options["nkadpc"] = False

        self.ffdFile = ar5FFDFile
        mesh_options = copy.copy(IDWarpDefOpts)
        mesh_options.update({"gridFile": options["gridFile"]})

        self.ap = copy.deepcopy(self.aero_prob)
        self.ap.evalFuncs = self.evalFuncs
        for dv in ["alpha", "mach", "P", "T"]:
            self.ap.addDV(dv)

        self.CFDSolver = ADFLOW_C(options=options, debug=True)
        self.CFDSolver.setMesh(USMesh_C(options=mesh_options))
        self.CFDSolver.setDVGeo(getDVGeo(self.ffdFile, isComplex=True), pointSetKwargs={"embTol": 1e-12, "eps": 1e-14})

        self.CFDSolver.getResidual(self.ap)

    def cmplx_test_aero_dvs(self):
        if not hasattr(self, "name"):
            return
        rtol = 1e-8
        atol = 5e-10

        for dv in ["alpha", "mach"]:
            funcsSens = defaultdict(lambda: {})
            setattr(self.ap, dv, getattr(self.ap, dv) + self.h * 1j)

            self.CFDSolver.resetFlow(self.ap)
            self.CFDSolver(self.ap, writeSolution=False)
            self.assert_solution_failure()

            funcs = {}
            self.CFDSolver.evalFunctions(self.ap, funcs)
            setattr(self.ap, dv, getattr(self.ap, dv) - self.h * 1j)

            for f in self.ap.evalFuncs:
                key = self.ap.name + "_" + f
                dv_key = dv + "_" + self.ap.name
                funcsSens[key][dv_key] = numpy.imag(funcs[key]) / self.h

        self.handler.root_add_dict("Eval Functions Sens:", funcsSens, rtol=rtol, atol=atol)

    def cmplx_test_geom_dvs(self):
        if not hasattr(self, "name"):
            return
        funcsSens = defaultdict(lambda: {})
        xRef = {"shape": numpy.zeros(112, dtype="D")}

        rtol = 5e-9
        atol = 5e-9

        for dv in ["shape"]:
            xRef[dv][0] += self.h * 1j

            self.CFDSolver.resetFlow(self.ap)
            self.CFDSolver.DVGeo.setDesignVars(xRef)
            self.CFDSolver(self.ap, writeSolution=False)
            self.assert_solution_failure()

            funcs = {}
            self.CFDSolver.evalFunctions(self.ap, funcs)
            xRef[dv][0] -= self.h * 1j

            for f in self.ap.evalFuncs:
                key = self.ap.name + "_" + f
                dv_key = dv
                funcsSens[key][dv_key] = numpy.imag(funcs[key]) / self.h

        self.handler.root_add_dict("Eval Functions Sens:", funcsSens, rtol=rtol, atol=atol)


if __name__ == "__main__":
    unittest.main()
