!        stub module — will be regenerated by tapenade
!  Run: make -f Makefile_tapenade ad_forward
!
module sagammaretheta_d
  use constants, only : realtype
  implicit none
  real(kind=realtype), dimension(:, :, :, :, :), allocatable :: qq

contains

! Stub forward-mode AD of Source (saGammaRetheta)
  subroutine source_d()
    implicit none
    ! Placeholder: regenerate with Tapenade ad_forward
  end subroutine source_d

! Stub forward-mode AD of Viscous (saGammaRetheta)
  subroutine viscous_d()
    implicit none
    ! Placeholder: regenerate with Tapenade ad_forward
  end subroutine viscous_d

! Stub forward-mode AD of ResScale (saGammaRetheta)
  subroutine resscale_d()
    implicit none
    ! Placeholder: regenerate with Tapenade ad_forward
  end subroutine resscale_d

end module sagammaretheta_d
