!        generated by tapenade     (inria, ecuador team)
!  tapenade 3.16 (develop) - 22 aug 2023 15:51
!
! this module contains the source code related to the sa turbulence
! model. it is slightly more modularized than the original which makes
! performing reverse mode ad simplier.
module sa_fast_b
  use constants
  implicit none
  real(kind=realtype) :: cv13, kar2inv, cw36, cb3inv
  real(kind=realtype), dimension(:, :, :), allocatable :: qq
  real(kind=realtype), dimension(:, :, :), pointer :: ddw, ww, ddvt
  real(kind=realtype), dimension(:, :), pointer :: rrlv
  real(kind=realtype), dimension(:, :), pointer :: dd2wall

contains
!  differentiation of sasource in reverse (adjoint) mode (with options noisize i4 dr8 r8):
!   gradient     of useful results: *w *rlv *scratch
!   with respect to varying inputs: *w *rlv *scratch
!   rw status of diff variables: *w:incr *rlv:incr *scratch:in-out
!   plus diff mem management of: w:in rlv:in scratch:in
  subroutine sasource_fast_b()
!
!  source terms.
!  determine the source term and its derivative w.r.t. nutilde
!  for all internal cells of the block.
!  remember that the sa field variable nutilde = w(i,j,k,itu1)
    use blockpointers
    use constants
    use paramturb
    use section
    use inputphysics
    use inputdiscretization, only : approxsa
    use flowvarrefstate
    use turbutils_fast_b
    implicit none
! local parameters
    real(kind=realtype), parameter :: f23=two*third
! local variables.
    integer(kind=inttype) :: i, j, k, nn, ii
    real(kind=realtype) :: fv1, fv2, ft2
    real(kind=realtype) :: fv1d, fv2d, ft2d
    real(kind=realtype) :: ss, sst, nu, dist2inv, chi, chi2, chi3
    real(kind=realtype) :: ssd, sstd, nud, chid, chi2d, chi3d
    real(kind=realtype) :: rr, gg, gg6, termfw, fwsa, term1, term2
    real(kind=realtype) :: rrd, ggd, gg6d, termfwd, fwsad, term1d, &
&   term2d
    real(kind=realtype) :: dfv1, dfv2, dft2, drr, dgg, dfw
    real(kind=realtype) :: dtterm2, darg_gamma, dttgamma
    real(kind=realtype) :: uux, uuy, uuz, vvx, vvy, vvz, wwx, wwy, wwz
    real(kind=realtype) :: uuxd, uuyd, uuzd, vvxd, vvyd, vvzd, wwxd, &
&   wwyd, wwzd
    real(kind=realtype) :: div2, fact, sxx, syy, szz, sxy, sxz, syz
    real(kind=realtype) :: div2d, sxxd, syyd, szzd, sxyd, sxzd, syzd
    real(kind=realtype) :: vortx, vorty, vortz
    real(kind=realtype) :: vortxd, vortyd, vortzd
    real(kind=realtype) :: omegax, omegay, omegaz
    real(kind=realtype) :: strainmag2, strainprod, vortprod
    real(kind=realtype) :: strainmag2d, strainprodd, vortprodd
! note: no local may end in _c: tapenade names its derivative <name>_cd/ and the
! autoedit scripts strip those suffixes (=> duplicate declaration). hence rethetacrit.
    real(kind=realtype) :: tterm2, rethetabase, rethetacrit, re_vorty, &
&   re_theta, tterm1, ttgamma
    real(kind=realtype) :: tterm2d, rethetacritd, re_vortyd, re_thetad, &
&   tterm1d, ttgammad
    real(kind=realtype) :: sqrtvort, stransition, k_max, arg_tanh, &
&   arg_gamma
    real(kind=realtype) :: sqrtvortd, stransitiond, k_maxd, arg_tanhd, &
&   arg_gammad
    real(kind=realtype) :: nwx, nwy, nwz, snn, laml, lam, lamlo, flam, &
&   mlammax, plammax, mp
    real(kind=realtype) :: snnd, lamld, lamd, lamlod, flamd
    real(kind=realtype) :: umap, umaplo, vadv, vfav, wmap, lammapped
    real(kind=realtype) :: umapd, umaplod, vadvd, vfavd, wmapd, &
&   lammappedd
    real(kind=realtype) :: gm1, pc, pip, pim, pjp, pjm, pkp, pkm, ppx, &
&   ppy, ppz
    real(kind=realtype) :: pcd, pipd, pimd, pjpd, pjmd, pkpd, pkmd, ppxd&
&   , ppyd, ppzd
    real(kind=realtype) :: velmagpg, uxh, uyh, uzh, dpds, ue2, ue2c, ue&
&   , dueds, ue2min, thetam
    real(kind=realtype) :: velmagpgd, uxhd, uyhd, uzhd, dpdsd, ue2d, &
&   ue2cd, ued, duedsd, thetamd
    real(kind=realtype) :: tx, ty, tz, tmag, tmagc, vdn
! wall-tangent floor (fraction of the unit free-stream direction):
! dp/ds -> 0 smoothly at the attachment line
    real(kind=realtype), parameter :: pgtangmin=0.05_realtype
! floor of the bernoulli edge velocity (stagnation region), fraction of u_inf
    real(kind=realtype), parameter :: pgueminfrac=0.05_realtype
! falkner-skan similarity map lambda_thetal(eta*) -> lambda_theta (docs/studies/22_bcm_pressure_gradie
! falkner_skan_map.py): adverse -a tanh(-u/b), favourable c (exp(u/d) - 1), blended over eps; u clipped
! to +-uclip before the exponential (u is o(1e3) outside the boundary layer).
! one parameter per line (tapenade wraps long declarations mid-token)
    real(kind=realtype), parameter :: pgmapa=0.06913_realtype
    real(kind=realtype), parameter :: pgmapb=0.03255_realtype
    real(kind=realtype), parameter :: pgmapc=0.09912_realtype
    real(kind=realtype), parameter :: pgmapd=0.04229_realtype
    real(kind=realtype), parameter :: pgmapeps=0.003_realtype
    real(kind=realtype), parameter :: pguclip=0.2_realtype
    real(kind=realtype), parameter :: pguclipneg=-0.2_realtype
    real(kind=realtype), parameter :: xminn=1.e-10_realtype
    intrinsic mod
    intrinsic sqrt
    intrinsic exp
    intrinsic min
    intrinsic max
    intrinsic tanh
    intrinsic log
    real(kind=realtype) :: y1
    real(kind=realtype) :: y1d
    real(kind=realtype) :: x1
    real(kind=realtype) :: x1d
    real(kind=realtype) :: min1
    real(kind=realtype) :: min1d
    real(kind=realtype) :: max1
    real(kind=realtype) :: max1d
    real(kind=realtype) :: max2
    real(kind=realtype) :: max2d
    real(kind=realtype) :: max3
    real(kind=realtype) :: max3d
    real(kind=realtype) :: max4
    real(kind=realtype) :: max4d
    real(kind=realtype) :: temp
    real(kind=realtype) :: tempd
    real(kind=realtype) :: temp0
    real(kind=realtype) :: tempd0
    real(kind=realtype) :: temp1
    real(kind=realtype) :: tempd1
    real(kind=realtype) :: temp2
    real(kind=realtype) :: tempd2
    real(kind=realtype) :: temp3
    real(kind=realtype) :: tempd3
    integer :: branch
! set model constants
    cv13 = rsacv1**3
    kar2inv = one/rsak**2
    cw36 = rsacw3**6
! determine the non-dimensional wheel speed of this block.
    omegax = timeref*sections(sectionid)%rotrate(1)
    omegay = timeref*sections(sectionid)%rotrate(2)
    omegaz = timeref*sections(sectionid)%rotrate(3)
! create switches to production term depending on the variable that
! should be used
    if (turbprod .eq. katolaunder) then
      stop
    else
      strainmag2d = 0.0_8
      ssd = 0.0_8
!$bwd-of ii-loop 
      do ii=0,nx*ny*nz-1
        i = mod(ii, nx) + 2
        j = mod(ii/nx, ny) + 2
        k = ii/(nx*ny) + 2
! compute the gradient of u in the cell center. use is made
! of the fact that the surrounding normals sum up to zero,
! such that the cell i,j,k does not give a contribution.
! the gradient is scaled by the factor 2*vol.
        uux = w(i+1, j, k, ivx)*si(i, j, k, 1) - w(i-1, j, k, ivx)*si(i-&
&         1, j, k, 1) + w(i, j+1, k, ivx)*sj(i, j, k, 1) - w(i, j-1, k, &
&         ivx)*sj(i, j-1, k, 1) + w(i, j, k+1, ivx)*sk(i, j, k, 1) - w(i&
&         , j, k-1, ivx)*sk(i, j, k-1, 1)
        uuy = w(i+1, j, k, ivx)*si(i, j, k, 2) - w(i-1, j, k, ivx)*si(i-&
&         1, j, k, 2) + w(i, j+1, k, ivx)*sj(i, j, k, 2) - w(i, j-1, k, &
&         ivx)*sj(i, j-1, k, 2) + w(i, j, k+1, ivx)*sk(i, j, k, 2) - w(i&
&         , j, k-1, ivx)*sk(i, j, k-1, 2)
        uuz = w(i+1, j, k, ivx)*si(i, j, k, 3) - w(i-1, j, k, ivx)*si(i-&
&         1, j, k, 3) + w(i, j+1, k, ivx)*sj(i, j, k, 3) - w(i, j-1, k, &
&         ivx)*sj(i, j-1, k, 3) + w(i, j, k+1, ivx)*sk(i, j, k, 3) - w(i&
&         , j, k-1, ivx)*sk(i, j, k-1, 3)
! idem for the gradient of v.
        vvx = w(i+1, j, k, ivy)*si(i, j, k, 1) - w(i-1, j, k, ivy)*si(i-&
&         1, j, k, 1) + w(i, j+1, k, ivy)*sj(i, j, k, 1) - w(i, j-1, k, &
&         ivy)*sj(i, j-1, k, 1) + w(i, j, k+1, ivy)*sk(i, j, k, 1) - w(i&
&         , j, k-1, ivy)*sk(i, j, k-1, 1)
        vvy = w(i+1, j, k, ivy)*si(i, j, k, 2) - w(i-1, j, k, ivy)*si(i-&
&         1, j, k, 2) + w(i, j+1, k, ivy)*sj(i, j, k, 2) - w(i, j-1, k, &
&         ivy)*sj(i, j-1, k, 2) + w(i, j, k+1, ivy)*sk(i, j, k, 2) - w(i&
&         , j, k-1, ivy)*sk(i, j, k-1, 2)
        vvz = w(i+1, j, k, ivy)*si(i, j, k, 3) - w(i-1, j, k, ivy)*si(i-&
&         1, j, k, 3) + w(i, j+1, k, ivy)*sj(i, j, k, 3) - w(i, j-1, k, &
&         ivy)*sj(i, j-1, k, 3) + w(i, j, k+1, ivy)*sk(i, j, k, 3) - w(i&
&         , j, k-1, ivy)*sk(i, j, k-1, 3)
! and for the gradient of w.
        wwx = w(i+1, j, k, ivz)*si(i, j, k, 1) - w(i-1, j, k, ivz)*si(i-&
&         1, j, k, 1) + w(i, j+1, k, ivz)*sj(i, j, k, 1) - w(i, j-1, k, &
&         ivz)*sj(i, j-1, k, 1) + w(i, j, k+1, ivz)*sk(i, j, k, 1) - w(i&
&         , j, k-1, ivz)*sk(i, j, k-1, 1)
        wwy = w(i+1, j, k, ivz)*si(i, j, k, 2) - w(i-1, j, k, ivz)*si(i-&
&         1, j, k, 2) + w(i, j+1, k, ivz)*sj(i, j, k, 2) - w(i, j-1, k, &
&         ivz)*sj(i, j-1, k, 2) + w(i, j, k+1, ivz)*sk(i, j, k, 2) - w(i&
&         , j, k-1, ivz)*sk(i, j, k-1, 2)
        wwz = w(i+1, j, k, ivz)*si(i, j, k, 3) - w(i-1, j, k, ivz)*si(i-&
&         1, j, k, 3) + w(i, j+1, k, ivz)*sj(i, j, k, 3) - w(i, j-1, k, &
&         ivz)*sj(i, j-1, k, 3) + w(i, j, k+1, ivz)*sk(i, j, k, 3) - w(i&
&         , j, k-1, ivz)*sk(i, j, k-1, 3)
! compute the components of the stress tensor.
! the combination of the current scaling of the velocity
! gradients (2*vol) and the definition of the stress tensor,
! leads to the factor 1/(4*vol).
        fact = fourth/vol(i, j, k)
        if (turbprod .eq. strain) then
          sxx = two*fact*uux
          syy = two*fact*vvy
          szz = two*fact*wwz
          sxy = fact*(uuy+vvx)
          sxz = fact*(uuz+wwx)
          syz = fact*(vvz+wwy)
! compute 2/3 * divergence of velocity squared
          div2 = f23*(sxx+syy+szz)**2
! compute strain production term
          strainmag2 = two*(sxy**2+sxz**2+syz**2) + sxx**2 + syy**2 + &
&           szz**2
          strainprod = two*strainmag2 - div2
          ss = sqrt(strainprod)
          call pushcontrol2b(0)
        else if (turbprod .eq. vorticity) then
! compute the three components of the vorticity vector.
! substract the part coming from the rotating frame.
          vortx = two*fact*(wwy-vvz) - two*omegax
          vorty = two*fact*(uuz-wwx) - two*omegay
          vortz = two*fact*(vvx-uuy) - two*omegaz
! compute the vorticity production term
          vortprod = vortx**2 + vorty**2 + vortz**2
! first take the square root of the production term to
! obtain the correct production term for spalart-allmaras.
! we do this to avoid if statements.
          ss = sqrt(vortprod)
          call pushcontrol2b(1)
        else
          call pushcontrol2b(2)
        end if
! compute the laminar kinematic viscosity, the inverse of
! wall distance squared, the ratio chi (ratio of nutilde
! and nu) and the functions fv1 and fv2. the latter corrects
! the production term near a viscous wall.
        nu = rlv(i, j, k)/w(i, j, k, irho)
        dist2inv = one/d2wall(i, j, k)**2
        chi = w(i, j, k, itu1)/nu
        chi2 = chi*chi
        chi3 = chi*chi2
        fv1 = chi3/(chi3+cv13)
        fv2 = one - chi/(one+chi*fv1)
! the function ft2, which is designed to keep a laminar
! solution laminar. when running in fully turbulent mode
! this function should be set to 0.0.
        if (useft2sa) then
          ft2 = rsact3*exp(-(rsact4*chi2))
myIntPtr = myIntPtr + 1
 myIntStack(myIntPtr) = 0
        else
          ft2 = zero
myIntPtr = myIntPtr + 1
 myIntStack(myIntPtr) = 1
        end if
! correct the production term to account for the influence
! of the wall.
        sst = ss + w(i, j, k, itu1)*fv2*kar2inv*dist2inv
! add rotation term (userotationsa defined in inputparams.f90)
        if (userotationsa) then
          y1 = sqrt(two*strainmag2)
          if (zero .gt. y1) then
            min1 = y1
myIntPtr = myIntPtr + 1
 myIntStack(myIntPtr) = 0
          else
            min1 = zero
myIntPtr = myIntPtr + 1
 myIntStack(myIntPtr) = 1
          end if
          sst = sst + rsacrot*min1
myIntPtr = myIntPtr + 1
 myIntStack(myIntPtr) = 1
        else
myIntPtr = myIntPtr + 1
 myIntStack(myIntPtr) = 0
        end if
        if (sst .lt. xminn) then
          sst = xminn
myIntPtr = myIntPtr + 1
 myIntStack(myIntPtr) = 0
        else
myIntPtr = myIntPtr + 1
 myIntStack(myIntPtr) = 1
          sst = sst
        end if
! compute the function fw. the argument rr is cut off at 10
! to avoid numerical problems. this is ok, because the
! asymptotical value of fw is then already reached.
        rr = w(i, j, k, itu1)*kar2inv*dist2inv/sst
        if (rr .gt. 10.0_realtype) then
          rr = 10.0_realtype
myIntPtr = myIntPtr + 1
 myIntStack(myIntPtr) = 0
        else
myIntPtr = myIntPtr + 1
 myIntStack(myIntPtr) = 1
          rr = rr
        end if
        gg = rr + rsacw2*(rr**6-rr)
        gg6 = gg**6
        termfw = ((one+cw36)/(gg6+cw36))**sixth
        fwsa = gg*termfw
        ttgamma = one
        if (use_sabcm) then
! compute the three components of the vorticity vector.
! substract the part coming from the rotating frame.
          vortx = two*fact*(wwy-vvz) - two*omegax
          vorty = two*fact*(uuz-wwx) - two*omegay
          vortz = two*fact*(vvx-uuy) - two*omegaz
! compute the vorticity production term
          vortprod = vortx**2 + vorty**2 + vortz**2
! first take the square root of the production term to
! obtain the correct production term for spalart-allmaras.
! we do this to avoid if statements.
          sqrtvort = sqrt(vortprod)
! tterm2 (small values ~0.01)
          tterm2 = fv1*chi/sabcm_const2
! re_theta critical
          rethetabase = 803.73_realtype*(sabcm_tu+0.6067_realtype)**(-&
&           1.027_realtype)
! pressure-gradient sensor (menter 2015 lambda_thetal with the
! wall normal n = nwall, langtry f(lambda) as in the sa-gamma-retheta
! model). off => flam = 1 and rethetacrit = rethetabase exactly.
          flam = one
          if (sabcm_pg) then
            nwx = nwall(1, i, j, k)
            nwy = nwall(2, i, j, k)
            nwz = nwall(3, i, j, k)
! n . grad(u) . n ; true gradient = two*fact*(uu.), fact = fourth/vol
            snn = two*fact*(nwx*(nwx*uux+nwy*uuy+nwz*uuz)+nwy*(nwx*vvx+&
&             nwy*vvy+nwz*vvz)+nwz*(nwx*wwx+nwy*wwy+nwz*wwz))
! no reynolds factor: nu = rlv/rho is non-dimensional with
! l_ref = 1 m, same convention as re_vorty below.
            if (sabcm_pg_sensor .ge. 2) then
! wall-pressure-gradient sensors: du_e/ds with u_e from bernoulli and the
! local pressure (p ~ p_wall across the layer), s = velocity direction, p from w (constant cp).
! k = (thetahat/eta*)^2 of the blasius profile = 0.05064: lambda_theta of falkner-skan to +-5 %,
! no offset (u_e' = 0 for blasius), no gain. independent of the velocity profile => no
! transition/sensor feedback (docs/studies/22_bcm_pressure_gradient/falkner_skan_psensor.py).
              gm1 = gammaconstant - one
              pc = gm1*(w(i, j, k, irhoe)-half*w(i, j, k, irho)*(w(i, j&
&               , k, ivx)**2+w(i, j, k, ivy)**2+w(i, j, k, ivz)**2))
              pip = gm1*(w(i+1, j, k, irhoe)-half*w(i+1, j, k, irho)*(w(&
&               i+1, j, k, ivx)**2+w(i+1, j, k, ivy)**2+w(i+1, j, k, ivz&
&               )**2))
              pim = gm1*(w(i-1, j, k, irhoe)-half*w(i-1, j, k, irho)*(w(&
&               i-1, j, k, ivx)**2+w(i-1, j, k, ivy)**2+w(i-1, j, k, ivz&
&               )**2))
              pjp = gm1*(w(i, j+1, k, irhoe)-half*w(i, j+1, k, irho)*(w(&
&               i, j+1, k, ivx)**2+w(i, j+1, k, ivy)**2+w(i, j+1, k, ivz&
&               )**2))
              pjm = gm1*(w(i, j-1, k, irhoe)-half*w(i, j-1, k, irho)*(w(&
&               i, j-1, k, ivx)**2+w(i, j-1, k, ivy)**2+w(i, j-1, k, ivz&
&               )**2))
              pkp = gm1*(w(i, j, k+1, irhoe)-half*w(i, j, k+1, irho)*(w(&
&               i, j, k+1, ivx)**2+w(i, j, k+1, ivy)**2+w(i, j, k+1, ivz&
&               )**2))
              pkm = gm1*(w(i, j, k-1, irhoe)-half*w(i, j, k-1, irho)*(w(&
&               i, j, k-1, ivx)**2+w(i, j, k-1, ivy)**2+w(i, j, k-1, ivz&
&               )**2))
              ppx = pip*si(i, j, k, 1) - pim*si(i-1, j, k, 1) + pjp*sj(i&
&               , j, k, 1) - pjm*sj(i, j-1, k, 1) + pkp*sk(i, j, k, 1) -&
&               pkm*sk(i, j, k-1, 1)
              ppy = pip*si(i, j, k, 2) - pim*si(i-1, j, k, 2) + pjp*sj(i&
&               , j, k, 2) - pjm*sj(i, j-1, k, 2) + pkp*sk(i, j, k, 2) -&
&               pkm*sk(i, j, k-1, 2)
              ppz = pip*si(i, j, k, 3) - pim*si(i-1, j, k, 3) + pjp*sj(i&
&               , j, k, 3) - pjm*sj(i, j-1, k, 3) + pkp*sk(i, j, k, 3) -&
&               pkm*sk(i, j, k-1, 3)
              if (sabcm_pg_sdir .eq. 2) then
myIntPtr = myIntPtr + 1
 myIntStack(myIntPtr) = 1
! edge-streamline direction = wall tangent oriented by the free stream (never
! reversed inside separation bubbles): t = e_inf - (e_inf.n) n, s = t/max(|t|, tmin)
                vdn = veldirfreestream(1)*nwx + veldirfreestream(2)*nwy &
&                 + veldirfreestream(3)*nwz
                tx = veldirfreestream(1) - vdn*nwx
                ty = veldirfreestream(2) - vdn*nwy
                tz = veldirfreestream(3) - vdn*nwz
                tmag = sqrt(tx**2 + ty**2 + tz**2)
                tmagc = smoothminmax(tmag, pgtangmin, sabcm_pg_p)
                uxh = tx/tmagc
                uyh = ty/tmagc
                uzh = tz/tmagc
              else
                velmagpg = sqrt(w(i, j, k, ivx)**2 + w(i, j, k, ivy)**2 &
&                 + w(i, j, k, ivz)**2)
                if (velmagpg .lt. xminn) then
myIntPtr = myIntPtr + 1
 myIntStack(myIntPtr) = 0
                  max1 = xminn
                else
                  max1 = velmagpg
myIntPtr = myIntPtr + 1
 myIntStack(myIntPtr) = 1
                end if
                uxh = w(i, j, k, ivx)/max1
                if (velmagpg .lt. xminn) then
myIntPtr = myIntPtr + 1
 myIntStack(myIntPtr) = 0
                  max2 = xminn
                else
                  max2 = velmagpg
myIntPtr = myIntPtr + 1
 myIntStack(myIntPtr) = 1
                end if
                uyh = w(i, j, k, ivy)/max2
                if (velmagpg .lt. xminn) then
                  max3 = xminn
myIntPtr = myIntPtr + 1
 myIntStack(myIntPtr) = 0
                else
                  max3 = velmagpg
myIntPtr = myIntPtr + 1
 myIntStack(myIntPtr) = 1
                end if
                uzh = w(i, j, k, ivz)/max3
myIntPtr = myIntPtr + 1
 myIntStack(myIntPtr) = 0
              end if
              dpds = two*fact*(uxh*ppx+uyh*ppy+uzh*ppz)
              ue2 = uinf**2 + two*(pinfcorr-pc)/rhoinf
              ue2min = (pgueminfrac*uinf)**2
              if (ue2 .lt. ue2min) then
                ue2c = ue2min
myIntPtr = myIntPtr + 1
 myIntStack(myIntPtr) = 0
              else
                ue2c = ue2
myIntPtr = myIntPtr + 1
 myIntStack(myIntPtr) = 1
              end if
              ue = sqrt(ue2c)
              dueds = -(dpds/(rhoinf*ue))
              if (sabcm_pg_sensor .eq. 3) then
! sensor 3: reference-model definition, theta = re_theta_c(tu)*nu/u_e (p&z eqs. 10-14:
! theta_t = re_theta_t nu/u) -> lambda = theta^2 u_e'/nu, uniform across the layer.
                thetam = rethetabase*nu/ue
                laml = thetam**2/nu*dueds
                call pushcontrol2b(0)
              else
! sensor 2: physical theta ~ d at the re_v peak, k = (thetahat/eta*)^2 blasius
                laml = sabcm_pg_k*(d2wall(i, j, k)**2/nu)*dueds
                call pushcontrol2b(1)
              end if
            else
              laml = -(sabcm_pg_coef*(d2wall(i, j, k)**2/nu)*snn) + &
&               sabcm_pg_off
              call pushcontrol2b(2)
            end if
! smooth clip of gain*laml to [-lammax, lammax] (distinct
! targets, not in place: keeps the fast-reverse ad exact).
! module variables are copied to locals before being passed to the
! differentiated helpers (tapenade otherwise emits a seed for them).
            mlammax = -sabcm_pg_lammax
            plammax = sabcm_pg_lammax
            mp = -sabcm_pg_p
            if (sabcm_pg_sensor .ge. 2) then
! already lambda_theta (no gain/map)
              lammapped = laml
              call pushcontrol2b(0)
            else if (sabcm_pg_map .eq. 2) then
! exact similarity map (no free gain): clip u, two analytic branches, smooth blend
              umaplo = smoothminmax(laml, pguclipneg, sabcm_pg_p)
              umap = smoothminmax(umaplo, pguclip, mp)
              vadv = pgmapa*tanh(umap/pgmapb)
              vfav = pgmapc*(exp(umap/pgmapd)-one)
              wmap = half*(one+tanh(umap/pgmapeps))
              lammapped = (one-wmap)*vadv + wmap*vfav
              call pushcontrol2b(1)
            else
              lammapped = sabcm_pg_gain*laml
              call pushcontrol2b(2)
            end if
            lamlo = smoothminmax(lammapped, mlammax, sabcm_pg_p)
            lam = smoothminmax(lamlo, plammax, mp)
            flam = bcmflambda(sabcm_tu, lam, sabcm_pg_p)
myIntPtr = myIntPtr + 1
 myIntStack(myIntPtr) = 0
          else
myIntPtr = myIntPtr + 1
 myIntStack(myIntPtr) = 1
          end if
! distinct target (never rethetacrit = rethetacrit*flam): the fast-reverse ad has no
! push/pop stack, an in-place update would use the overwritten value in flamd.
! flam = one when sabcm_pg is off: the product is exact, pg-off stays bit-identical.
          rethetacrit = rethetabase*flam
! re_theta actual
          re_vorty = sqrtvort*w(i, j, k, irho)/rlv(i, j, k)*d2wall(i, j&
&           , k)**2
          re_theta = re_vorty/2.193_realtype
! tterm1 (can be huge ~1e5)
          tterm1 = (re_theta-rethetacrit)/(rethetacrit*sabcm_const1)
          if (sabcm_exp) then
            if (tterm1 .lt. zero) then
              tterm1 = zero
myIntPtr = myIntPtr + 1
 myIntStack(myIntPtr) = 0
            else
myIntPtr = myIntPtr + 1
 myIntStack(myIntPtr) = 1
              tterm1 = tterm1
            end if
            if (tterm2 .lt. zero) then
              max4 = zero
myIntPtr = myIntPtr + 1
 myIntStack(myIntPtr) = 0
            else
              max4 = tterm2
myIntPtr = myIntPtr + 1
 myIntStack(myIntPtr) = 1
            end if
            arg_gamma = sqrt(tterm1) + sqrt(max4)
            ttgamma = one - exp(-arg_gamma)
            if (ttgamma .lt. zero) then
              x1 = zero
myIntPtr = myIntPtr + 1
 myIntStack(myIntPtr) = 0
            else
              x1 = ttgamma
myIntPtr = myIntPtr + 1
 myIntStack(myIntPtr) = 1
            end if
            if (x1 .gt. one) then
              ttgamma = one
              call pushcontrol2b(2)
            else
              ttgamma = x1
              call pushcontrol2b(1)
            end if
          else
! differentiable reformulation: ks-smoothed max in term1, tanh intermittency
            stransition = sabcm_maxsmooth*tterm1
            if (stransition .lt. xminn) then
myIntPtr = myIntPtr + 1
 myIntStack(myIntPtr) = 0
              k_max = xminn
            else
              k_max = stransition
myIntPtr = myIntPtr + 1
 myIntStack(myIntPtr) = 1
            end if
            tterm1 = (k_max+log(exp(stransition-k_max)+exp(-k_max)))/&
&             sabcm_maxsmooth
! current tanh-based formula
            arg_tanh = (tterm1+tterm2-sabcm_s0_tanh)/sabcm_fsmooth
            ttgamma = 0.5_realtype*(1.0_realtype+tanh(arg_tanh))
            call pushcontrol2b(0)
          end if
          ft2 = zero
        else
          call pushcontrol2b(3)
        end if
! compute the source term; some terms are saved for the
! linearization. the source term is stored in dvt.
        if (approxsa) then
myIntPtr = myIntPtr + 1
 myIntStack(myIntPtr) = 0
          term1 = zero
        else
          term1 = ttgamma*rsacb1*(one-ft2)*ss
myIntPtr = myIntPtr + 1
 myIntStack(myIntPtr) = 1
        end if
        term2 = dist2inv*(kar2inv*ttgamma*rsacb1*((one-ft2)*fv2+ft2)-&
&         rsacw1*fwsa)
        temp2 = w(i, j, k, itu1)
        tempd3 = w(i, j, k, itu1)*scratchd(i, j, k, idvt)
        wd(i, j, k, itu1) = wd(i, j, k, itu1) + (term1+term2*temp2)*&
&         scratchd(i, j, k, idvt) + term2*tempd3
        scratchd(i, j, k, idvt) = 0.0_8
        term1d = tempd3
        term2d = temp2*tempd3
        tempd3 = kar2inv*rsacb1*dist2inv*term2d
        fwsad = -(rsacw1*dist2inv*term2d)
        ttgammad = ((one-ft2)*fv2+ft2)*tempd3
        tempd2 = ttgamma*tempd3
        ft2d = (1.0-fv2)*tempd2
        fv2d = (one-ft2)*tempd2
branch = myIntStack(myIntPtr)
 myIntPtr = myIntPtr - 1
        if (branch .ne. 0) then
          ft2d = ft2d - ttgamma*ss*rsacb1*term1d
          tempd3 = (one-ft2)*rsacb1*term1d
          ttgammad = ttgammad + ss*tempd3
          ssd = ssd + ttgamma*tempd3
        end if
        call popcontrol2b(branch)
        if (branch .lt. 2) then
          if (branch .eq. 0) then
            arg_tanhd = (1.0-tanh(arg_tanh)**2)*0.5_realtype*ttgammad
            tterm1d = arg_tanhd/sabcm_fsmooth
            tterm2d = arg_tanhd/sabcm_fsmooth
            tempd3 = tterm1d/((exp(stransition-k_max)+exp(-k_max))*&
&             sabcm_maxsmooth)
            tempd2 = exp(stransition-k_max)*tempd3
            k_maxd = tterm1d/sabcm_maxsmooth - exp(-k_max)*tempd3 - &
&             tempd2
            stransitiond = tempd2
branch = myIntStack(myIntPtr)
 myIntPtr = myIntPtr - 1
            if (branch .ne. 0) stransitiond = stransitiond + k_maxd
            tterm1d = sabcm_maxsmooth*stransitiond
            goto 100
          else
            x1d = ttgammad
          end if
        else if (branch .eq. 2) then
          x1d = 0.0_8
        else
          nud = 0.0_8
          fv1d = 0.0_8
          wwxd = 0.0_8
          chid = 0.0_8
          wwyd = 0.0_8
          wwzd = 0.0_8
          vvxd = 0.0_8
          vvyd = 0.0_8
          vvzd = 0.0_8
          uuxd = 0.0_8
          uuyd = 0.0_8
          uuzd = 0.0_8
          goto 120
        end if
branch = myIntStack(myIntPtr)
 myIntPtr = myIntPtr - 1
        if (branch .eq. 0) then
          ttgammad = 0.0_8
        else
          ttgammad = x1d
        end if
        arg_gammad = exp(-arg_gamma)*ttgammad
        if (tterm1 .eq. 0.0_8) then
          tterm1d = 0.0_8
        else
          tterm1d = arg_gammad/(2.0*sqrt(tterm1))
        end if
        if (max4 .eq. 0.0_8) then
          max4d = 0.0_8
        else
          max4d = arg_gammad/(2.0*sqrt(max4))
        end if
branch = myIntStack(myIntPtr)
 myIntPtr = myIntPtr - 1
        if (branch .eq. 0) then
          tterm2d = 0.0_8
        else
          tterm2d = max4d
        end if
branch = myIntStack(myIntPtr)
 myIntPtr = myIntPtr - 1
        if (branch .eq. 0) tterm1d = 0.0_8
 100    tempd3 = tterm1d/(sabcm_const1*rethetacrit)
        re_thetad = tempd3
        rethetacritd = -(((re_theta-rethetacrit)/rethetacrit+1.0)*tempd3&
&         )
        re_vortyd = re_thetad/2.193_realtype
        temp2 = sqrtvort/rlv(i, j, k)
        tempd3 = d2wall(i, j, k)**2*re_vortyd
        wd(i, j, k, irho) = wd(i, j, k, irho) + temp2*tempd3
        tempd2 = w(i, j, k, irho)*tempd3/rlv(i, j, k)
        sqrtvortd = tempd2
        rlvd(i, j, k) = rlvd(i, j, k) - temp2*tempd2
        flamd = rethetabase*rethetacritd
branch = myIntStack(myIntPtr)
 myIntPtr = myIntPtr - 1
        if (branch .eq. 0) then
          call bcmflambda_fast_b(sabcm_tu, lam, lamd, sabcm_pg_p, flamd)
          call smoothminmax_fast_b(lamlo, lamlod, plammax, mp, lamd)
          call smoothminmax_fast_b(lammapped, lammappedd, mlammax, &
&                            sabcm_pg_p, lamlod)
          call popcontrol2b(branch)
          if (branch .eq. 0) then
            lamld = lammappedd
          else if (branch .eq. 1) then
            wmapd = (vfav-vadv)*lammappedd
            vadvd = (one-wmap)*lammappedd
            vfavd = wmap*lammappedd
            umapd = (1.0-tanh(umap/pgmapeps)**2)*half*wmapd/pgmapeps + &
&             exp(umap/pgmapd)*pgmapc*vfavd/pgmapd + (1.0-tanh(umap/&
&             pgmapb)**2)*pgmapa*vadvd/pgmapb
            call smoothminmax_fast_b(umaplo, umaplod, pguclip, mp, umapd&
&                             )
            call smoothminmax_fast_b(laml, lamld, pguclipneg, sabcm_pg_p&
&                              , umaplod)
          else
            lamld = sabcm_pg_gain*lammappedd
          end if
          call popcontrol2b(branch)
          if (branch .eq. 0) then
            thetamd = 2*thetam*dueds*lamld/nu
            tempd3 = thetam**2*lamld/nu
            duedsd = tempd3
            nud = -(dueds*tempd3/nu)
            tempd3 = rethetabase*thetamd/ue
            nud = nud + tempd3
            ued = -(nu*tempd3/ue)
          else if (branch .eq. 1) then
            tempd3 = sabcm_pg_k*d2wall(i, j, k)**2*lamld/nu
            duedsd = tempd3
            nud = -(dueds*tempd3/nu)
            ued = 0.0_8
          else
            tempd3 = -(sabcm_pg_coef*d2wall(i, j, k)**2*lamld/nu)
            snnd = tempd3
            nud = -(snn*tempd3/nu)
            goto 110
          end if
          tempd3 = -(duedsd/(rhoinf*ue))
          dpdsd = tempd3
          ued = ued - dpds*tempd3/ue
          if (ue2c .eq. 0.0_8) then
            ue2cd = 0.0_8
          else
            ue2cd = ued/(2.0*sqrt(ue2c))
          end if
branch = myIntStack(myIntPtr)
 myIntPtr = myIntPtr - 1
          if (branch .eq. 0) then
            ue2d = 0.0_8
          else
            ue2d = ue2cd
          end if
          pcd = -(two*ue2d/rhoinf)
          tempd3 = two*fact*dpdsd
          uxhd = ppx*tempd3
          ppxd = uxh*tempd3
          uyhd = ppy*tempd3
          ppyd = uyh*tempd3
          uzhd = ppz*tempd3
          ppzd = uzh*tempd3
branch = myIntStack(myIntPtr)
 myIntPtr = myIntPtr - 1
          if (branch .eq. 0) then
            wd(i, j, k, ivz) = wd(i, j, k, ivz) + uzhd/max3
            max3d = -(w(i, j, k, ivz)*uzhd/max3**2)
branch = myIntStack(myIntPtr)
 myIntPtr = myIntPtr - 1
            if (branch .eq. 0) then
              velmagpgd = 0.0_8
            else
              velmagpgd = max3d
            end if
            wd(i, j, k, ivy) = wd(i, j, k, ivy) + uyhd/max2
            max2d = -(w(i, j, k, ivy)*uyhd/max2**2)
branch = myIntStack(myIntPtr)
 myIntPtr = myIntPtr - 1
            if (branch .ne. 0) velmagpgd = velmagpgd + max2d
            wd(i, j, k, ivx) = wd(i, j, k, ivx) + uxhd/max1
            max1d = -(w(i, j, k, ivx)*uxhd/max1**2)
branch = myIntStack(myIntPtr)
 myIntPtr = myIntPtr - 1
            if (branch .ne. 0) velmagpgd = velmagpgd + max1d
            temp3 = w(i, j, k, ivz)
            temp2 = w(i, j, k, ivy)
            temp1 = w(i, j, k, ivx)
            if (temp1**2 + temp2**2 + temp3**2 .eq. 0.0_8) then
              tempd0 = 0.0_8
            else
              tempd0 = velmagpgd/(2.0*sqrt(temp1**2+temp2**2+temp3**2))
            end if
            wd(i, j, k, ivx) = wd(i, j, k, ivx) + 2*temp1*tempd0
            wd(i, j, k, ivy) = wd(i, j, k, ivy) + 2*temp2*tempd0
            wd(i, j, k, ivz) = wd(i, j, k, ivz) + 2*temp3*tempd0
          end if
          pipd = si(i, j, k, 3)*ppzd + si(i, j, k, 2)*ppyd + si(i, j, k&
&           , 1)*ppxd
          pimd = -(si(i-1, j, k, 3)*ppzd) - si(i-1, j, k, 2)*ppyd - si(i&
&           -1, j, k, 1)*ppxd
          pjpd = sj(i, j, k, 3)*ppzd + sj(i, j, k, 2)*ppyd + sj(i, j, k&
&           , 1)*ppxd
          pkpd = sk(i, j, k, 3)*ppzd + sk(i, j, k, 2)*ppyd + sk(i, j, k&
&           , 1)*ppxd
          pjmd = -(sj(i, j-1, k, 3)*ppzd) - sj(i, j-1, k, 2)*ppyd - sj(i&
&           , j-1, k, 1)*ppxd
          pkmd = -(sk(i, j, k-1, 3)*ppzd) - sk(i, j, k-1, 2)*ppyd - sk(i&
&           , j, k-1, 1)*ppxd
          temp2 = w(i, j, k-1, ivz)
          temp1 = w(i, j, k-1, ivy)
          temp0 = w(i, j, k-1, ivx)
          tempd3 = gm1*pkmd
          wd(i, j, k-1, irhoe) = wd(i, j, k-1, irhoe) + tempd3
          wd(i, j, k-1, irho) = wd(i, j, k-1, irho) - (temp0**2+temp1**2&
&           +temp2**2)*half*tempd3
          tempd = -(w(i, j, k-1, irho)*half*tempd3)
          wd(i, j, k-1, ivx) = wd(i, j, k-1, ivx) + 2*temp0*tempd
          wd(i, j, k-1, ivy) = wd(i, j, k-1, ivy) + 2*temp1*tempd
          wd(i, j, k-1, ivz) = wd(i, j, k-1, ivz) + 2*temp2*tempd
          temp2 = w(i, j, k+1, ivz)
          temp1 = w(i, j, k+1, ivy)
          temp0 = w(i, j, k+1, ivx)
          tempd3 = gm1*pkpd
          wd(i, j, k+1, irhoe) = wd(i, j, k+1, irhoe) + tempd3
          wd(i, j, k+1, irho) = wd(i, j, k+1, irho) - (temp0**2+temp1**2&
&           +temp2**2)*half*tempd3
          tempd = -(w(i, j, k+1, irho)*half*tempd3)
          wd(i, j, k+1, ivx) = wd(i, j, k+1, ivx) + 2*temp0*tempd
          wd(i, j, k+1, ivy) = wd(i, j, k+1, ivy) + 2*temp1*tempd
          wd(i, j, k+1, ivz) = wd(i, j, k+1, ivz) + 2*temp2*tempd
          temp2 = w(i, j-1, k, ivz)
          temp1 = w(i, j-1, k, ivy)
          temp0 = w(i, j-1, k, ivx)
          tempd3 = gm1*pjmd
          wd(i, j-1, k, irhoe) = wd(i, j-1, k, irhoe) + tempd3
          wd(i, j-1, k, irho) = wd(i, j-1, k, irho) - (temp0**2+temp1**2&
&           +temp2**2)*half*tempd3
          tempd = -(w(i, j-1, k, irho)*half*tempd3)
          wd(i, j-1, k, ivx) = wd(i, j-1, k, ivx) + 2*temp0*tempd
          wd(i, j-1, k, ivy) = wd(i, j-1, k, ivy) + 2*temp1*tempd
          wd(i, j-1, k, ivz) = wd(i, j-1, k, ivz) + 2*temp2*tempd
          temp2 = w(i, j+1, k, ivz)
          temp1 = w(i, j+1, k, ivy)
          temp0 = w(i, j+1, k, ivx)
          tempd3 = gm1*pjpd
          wd(i, j+1, k, irhoe) = wd(i, j+1, k, irhoe) + tempd3
          wd(i, j+1, k, irho) = wd(i, j+1, k, irho) - (temp0**2+temp1**2&
&           +temp2**2)*half*tempd3
          tempd = -(w(i, j+1, k, irho)*half*tempd3)
          wd(i, j+1, k, ivx) = wd(i, j+1, k, ivx) + 2*temp0*tempd
          wd(i, j+1, k, ivy) = wd(i, j+1, k, ivy) + 2*temp1*tempd
          wd(i, j+1, k, ivz) = wd(i, j+1, k, ivz) + 2*temp2*tempd
          temp2 = w(i-1, j, k, ivz)
          temp1 = w(i-1, j, k, ivy)
          temp0 = w(i-1, j, k, ivx)
          tempd3 = gm1*pimd
          wd(i-1, j, k, irhoe) = wd(i-1, j, k, irhoe) + tempd3
          wd(i-1, j, k, irho) = wd(i-1, j, k, irho) - (temp0**2+temp1**2&
&           +temp2**2)*half*tempd3
          tempd = -(w(i-1, j, k, irho)*half*tempd3)
          wd(i-1, j, k, ivx) = wd(i-1, j, k, ivx) + 2*temp0*tempd
          wd(i-1, j, k, ivy) = wd(i-1, j, k, ivy) + 2*temp1*tempd
          wd(i-1, j, k, ivz) = wd(i-1, j, k, ivz) + 2*temp2*tempd
          temp2 = w(i+1, j, k, ivz)
          temp1 = w(i+1, j, k, ivy)
          temp0 = w(i+1, j, k, ivx)
          tempd3 = gm1*pipd
          wd(i+1, j, k, irhoe) = wd(i+1, j, k, irhoe) + tempd3
          wd(i+1, j, k, irho) = wd(i+1, j, k, irho) - (temp0**2+temp1**2&
&           +temp2**2)*half*tempd3
          tempd = -(w(i+1, j, k, irho)*half*tempd3)
          wd(i+1, j, k, ivx) = wd(i+1, j, k, ivx) + 2*temp0*tempd
          wd(i+1, j, k, ivy) = wd(i+1, j, k, ivy) + 2*temp1*tempd
          wd(i+1, j, k, ivz) = wd(i+1, j, k, ivz) + 2*temp2*tempd
          temp1 = w(i, j, k, ivz)
          temp0 = w(i, j, k, ivy)
          temp = w(i, j, k, ivx)
          tempd2 = gm1*pcd
          wd(i, j, k, irhoe) = wd(i, j, k, irhoe) + tempd2
          wd(i, j, k, irho) = wd(i, j, k, irho) - (temp**2+temp0**2+&
&           temp1**2)*half*tempd2
          tempd3 = -(w(i, j, k, irho)*half*tempd2)
          wd(i, j, k, ivx) = wd(i, j, k, ivx) + 2*temp*tempd3
          wd(i, j, k, ivy) = wd(i, j, k, ivy) + 2*temp0*tempd3
          wd(i, j, k, ivz) = wd(i, j, k, ivz) + 2*temp1*tempd3
          snnd = 0.0_8
 110      tempd0 = two*fact*snnd
          tempd = nwx*tempd0
          tempd1 = nwy*tempd0
          tempd2 = nwz*tempd0
          wwxd = nwx*tempd2
          wwyd = nwy*tempd2
          wwzd = nwz*tempd2
          vvxd = nwx*tempd1
          vvyd = nwy*tempd1
          vvzd = nwz*tempd1
          uuxd = nwx*tempd
          uuyd = nwy*tempd
          uuzd = nwz*tempd
        else
          nud = 0.0_8
          wwxd = 0.0_8
          wwyd = 0.0_8
          wwzd = 0.0_8
          vvxd = 0.0_8
          vvyd = 0.0_8
          vvzd = 0.0_8
          uuxd = 0.0_8
          uuyd = 0.0_8
          uuzd = 0.0_8
        end if
        fv1d = chi*tterm2d/sabcm_const2
        chid = fv1*tterm2d/sabcm_const2
        if (vortprod .eq. 0.0_8) then
          vortprodd = 0.0_8
        else
          vortprodd = sqrtvortd/(2.0*sqrt(vortprod))
        end if
        vortxd = 2*vortx*vortprodd
        vortyd = 2*vorty*vortprodd
        vortzd = 2*vortz*vortprodd
        tempd0 = two*fact*vortzd
        vvxd = vvxd + tempd0
        uuyd = uuyd - tempd0
        tempd0 = two*fact*vortyd
        uuzd = uuzd + tempd0
        wwxd = wwxd - tempd0
        tempd0 = two*fact*vortxd
        wwyd = wwyd + tempd0
        vvzd = vvzd - tempd0
        ft2d = 0.0_8
 120    termfwd = gg*fwsad
        temp0 = (one+cw36)/(cw36+gg6)
        if (temp0 .le. 0.0_8 .and. (sixth .eq. 0.0_8 .or. sixth .ne. int&
&           (sixth))) then
          gg6d = 0.0_8
        else
          gg6d = -(temp0*sixth*temp0**(sixth-1)*termfwd/(cw36+gg6))
        end if
        ggd = termfw*fwsad + 6*gg**5*gg6d
        rrd = (6*rr**5*rsacw2-rsacw2+1.0)*ggd
branch = myIntStack(myIntPtr)
 myIntPtr = myIntPtr - 1
        if (branch .eq. 0) rrd = 0.0_8
        tempd0 = kar2inv*dist2inv*rrd/sst
        wd(i, j, k, itu1) = wd(i, j, k, itu1) + tempd0
        sstd = -(w(i, j, k, itu1)*tempd0/sst)
branch = myIntStack(myIntPtr)
 myIntPtr = myIntPtr - 1
        if (branch .eq. 0) sstd = 0.0_8
branch = myIntStack(myIntPtr)
 myIntPtr = myIntPtr - 1
        if (branch .ne. 0) then
          min1d = rsacrot*sstd
branch = myIntStack(myIntPtr)
 myIntPtr = myIntPtr - 1
          if (branch .eq. 0) then
            y1d = min1d
          else
            y1d = 0.0_8
          end if
          if (.not.two*strainmag2 .eq. 0.0_8) strainmag2d = strainmag2d &
&             + two*y1d/(2.0*sqrt(two*strainmag2))
        end if
        ssd = ssd + sstd
        tempd0 = kar2inv*dist2inv*sstd
        wd(i, j, k, itu1) = wd(i, j, k, itu1) + fv2*tempd0
        fv2d = fv2d + w(i, j, k, itu1)*tempd0
branch = myIntStack(myIntPtr)
 myIntPtr = myIntPtr - 1
        if (branch .eq. 0) then
          chi2d = -(rsact4*exp(-(rsact4*chi2))*rsact3*ft2d)
        else
          chi2d = 0.0_8
        end if
        tempd = -(fv2d/(one+chi*fv1))
        chid = chid + tempd
        tempd0 = -(chi*tempd/(one+chi*fv1))
        fv1d = fv1d + chi*tempd0
        tempd = fv1d/(cv13+chi3)
        chi3d = (1.0-chi3/(cv13+chi3))*tempd
        chi2d = chi2d + chi*chi3d
        chid = chid + fv1*tempd0 + chi2*chi3d + 2*chi*chi2d
        wd(i, j, k, itu1) = wd(i, j, k, itu1) + chid/nu
        nud = nud - w(i, j, k, itu1)*chid/nu**2
        temp = w(i, j, k, irho)
        rlvd(i, j, k) = rlvd(i, j, k) + nud/temp
        wd(i, j, k, irho) = wd(i, j, k, irho) - rlv(i, j, k)*nud/temp**2
        call popcontrol2b(branch)
        if (branch .eq. 0) then
          if (strainprod .eq. 0.0_8) then
            strainprodd = 0.0_8
          else
            strainprodd = ssd/(2.0*sqrt(strainprod))
          end if
          strainmag2d = strainmag2d + two*strainprodd
          div2d = -strainprodd
          tempd = two*strainmag2d
          sxyd = 2*sxy*tempd
          sxzd = 2*sxz*tempd
          syzd = 2*syz*tempd
          tempd = 2*(sxx+syy+szz)*f23*div2d
          sxxd = 2*sxx*strainmag2d + tempd
          syyd = 2*syy*strainmag2d + tempd
          szzd = 2*szz*strainmag2d + tempd
          vvzd = vvzd + fact*syzd
          wwyd = wwyd + fact*syzd
          uuzd = uuzd + fact*sxzd
          wwxd = wwxd + fact*sxzd
          uuyd = uuyd + fact*sxyd
          vvxd = vvxd + fact*sxyd
          wwzd = wwzd + two*fact*szzd
          vvyd = vvyd + two*fact*syyd
          uuxd = uuxd + two*fact*sxxd
          strainmag2d = 0.0_8
          ssd = 0.0_8
        else if (branch .eq. 1) then
          vortx = two*fact*(wwy-vvz) - two*omegax
          vorty = two*fact*(uuz-wwx) - two*omegay
          vortz = two*fact*(vvx-uuy) - two*omegaz
          vortprod = vortx**2 + vorty**2 + vortz**2
          if (vortprod .eq. 0.0_8) then
            vortprodd = 0.0_8
          else
            vortprodd = ssd/(2.0*sqrt(vortprod))
          end if
          vortxd = 2*vortx*vortprodd
          vortyd = 2*vorty*vortprodd
          vortzd = 2*vortz*vortprodd
          tempd = two*fact*vortzd
          vvxd = vvxd + tempd
          uuyd = uuyd - tempd
          tempd = two*fact*vortyd
          uuzd = uuzd + tempd
          wwxd = wwxd - tempd
          tempd = two*fact*vortxd
          wwyd = wwyd + tempd
          vvzd = vvzd - tempd
          ssd = 0.0_8
        end if
        wd(i, j, k-1, ivz) = wd(i, j, k-1, ivz) - sk(i, j, k-1, 3)*wwzd &
&         - sk(i, j, k-1, 2)*wwyd - sk(i, j, k-1, 1)*wwxd
        wd(i, j-1, k, ivz) = wd(i, j-1, k, ivz) - sj(i, j-1, k, 3)*wwzd &
&         - sj(i, j-1, k, 2)*wwyd - sj(i, j-1, k, 1)*wwxd
        wd(i, j, k+1, ivz) = wd(i, j, k+1, ivz) + sk(i, j, k, 3)*wwzd + &
&         sk(i, j, k, 2)*wwyd + sk(i, j, k, 1)*wwxd
        wd(i, j+1, k, ivz) = wd(i, j+1, k, ivz) + sj(i, j, k, 3)*wwzd + &
&         sj(i, j, k, 2)*wwyd + sj(i, j, k, 1)*wwxd
        wd(i-1, j, k, ivz) = wd(i-1, j, k, ivz) - si(i-1, j, k, 3)*wwzd &
&         - si(i-1, j, k, 2)*wwyd - si(i-1, j, k, 1)*wwxd
        wd(i+1, j, k, ivz) = wd(i+1, j, k, ivz) + si(i, j, k, 3)*wwzd + &
&         si(i, j, k, 2)*wwyd + si(i, j, k, 1)*wwxd
        wd(i, j, k-1, ivy) = wd(i, j, k-1, ivy) - sk(i, j, k-1, 3)*vvzd &
&         - sk(i, j, k-1, 2)*vvyd - sk(i, j, k-1, 1)*vvxd
        wd(i, j-1, k, ivy) = wd(i, j-1, k, ivy) - sj(i, j-1, k, 3)*vvzd &
&         - sj(i, j-1, k, 2)*vvyd - sj(i, j-1, k, 1)*vvxd
        wd(i, j, k+1, ivy) = wd(i, j, k+1, ivy) + sk(i, j, k, 3)*vvzd + &
&         sk(i, j, k, 2)*vvyd + sk(i, j, k, 1)*vvxd
        wd(i, j+1, k, ivy) = wd(i, j+1, k, ivy) + sj(i, j, k, 3)*vvzd + &
&         sj(i, j, k, 2)*vvyd + sj(i, j, k, 1)*vvxd
        wd(i-1, j, k, ivy) = wd(i-1, j, k, ivy) - si(i-1, j, k, 3)*vvzd &
&         - si(i-1, j, k, 2)*vvyd - si(i-1, j, k, 1)*vvxd
        wd(i+1, j, k, ivy) = wd(i+1, j, k, ivy) + si(i, j, k, 3)*vvzd + &
&         si(i, j, k, 2)*vvyd + si(i, j, k, 1)*vvxd
        wd(i, j, k-1, ivx) = wd(i, j, k-1, ivx) - sk(i, j, k-1, 3)*uuzd &
&         - sk(i, j, k-1, 2)*uuyd - sk(i, j, k-1, 1)*uuxd
        wd(i, j-1, k, ivx) = wd(i, j-1, k, ivx) - sj(i, j-1, k, 3)*uuzd &
&         - sj(i, j-1, k, 2)*uuyd - sj(i, j-1, k, 1)*uuxd
        wd(i, j, k+1, ivx) = wd(i, j, k+1, ivx) + sk(i, j, k, 3)*uuzd + &
&         sk(i, j, k, 2)*uuyd + sk(i, j, k, 1)*uuxd
        wd(i, j+1, k, ivx) = wd(i, j+1, k, ivx) + sj(i, j, k, 3)*uuzd + &
&         sj(i, j, k, 2)*uuyd + sj(i, j, k, 1)*uuxd
        wd(i-1, j, k, ivx) = wd(i-1, j, k, ivx) - si(i-1, j, k, 3)*uuzd &
&         - si(i-1, j, k, 2)*uuyd - si(i-1, j, k, 1)*uuxd
        wd(i+1, j, k, ivx) = wd(i+1, j, k, ivx) + si(i, j, k, 3)*uuzd + &
&         si(i, j, k, 2)*uuyd + si(i, j, k, 1)*uuxd
      end do
    end if
  end subroutine sasource_fast_b

  subroutine sasource()
!
!  source terms.
!  determine the source term and its derivative w.r.t. nutilde
!  for all internal cells of the block.
!  remember that the sa field variable nutilde = w(i,j,k,itu1)
    use blockpointers
    use constants
    use paramturb
    use section
    use inputphysics
    use inputdiscretization, only : approxsa
    use flowvarrefstate
    use turbutils_fast_b
    implicit none
! local parameters
    real(kind=realtype), parameter :: f23=two*third
! local variables.
    integer(kind=inttype) :: i, j, k, nn, ii
    real(kind=realtype) :: fv1, fv2, ft2
    real(kind=realtype) :: ss, sst, nu, dist2inv, chi, chi2, chi3
    real(kind=realtype) :: rr, gg, gg6, termfw, fwsa, term1, term2
    real(kind=realtype) :: dfv1, dfv2, dft2, drr, dgg, dfw
    real(kind=realtype) :: dtterm2, darg_gamma, dttgamma
    real(kind=realtype) :: uux, uuy, uuz, vvx, vvy, vvz, wwx, wwy, wwz
    real(kind=realtype) :: div2, fact, sxx, syy, szz, sxy, sxz, syz
    real(kind=realtype) :: vortx, vorty, vortz
    real(kind=realtype) :: omegax, omegay, omegaz
    real(kind=realtype) :: strainmag2, strainprod, vortprod
! note: no local may end in _c: tapenade names its derivative <name>_cd/ and the
! autoedit scripts strip those suffixes (=> duplicate declaration). hence rethetacrit.
    real(kind=realtype) :: tterm2, rethetabase, rethetacrit, re_vorty, &
&   re_theta, tterm1, ttgamma
    real(kind=realtype) :: sqrtvort, stransition, k_max, arg_tanh, &
&   arg_gamma
    real(kind=realtype) :: nwx, nwy, nwz, snn, laml, lam, lamlo, flam, &
&   mlammax, plammax, mp
    real(kind=realtype) :: umap, umaplo, vadv, vfav, wmap, lammapped
    real(kind=realtype) :: gm1, pc, pip, pim, pjp, pjm, pkp, pkm, ppx, &
&   ppy, ppz
    real(kind=realtype) :: velmagpg, uxh, uyh, uzh, dpds, ue2, ue2c, ue&
&   , dueds, ue2min, thetam
    real(kind=realtype) :: tx, ty, tz, tmag, tmagc, vdn
! wall-tangent floor (fraction of the unit free-stream direction):
! dp/ds -> 0 smoothly at the attachment line
    real(kind=realtype), parameter :: pgtangmin=0.05_realtype
! floor of the bernoulli edge velocity (stagnation region), fraction of u_inf
    real(kind=realtype), parameter :: pgueminfrac=0.05_realtype
! falkner-skan similarity map lambda_thetal(eta*) -> lambda_theta (docs/studies/22_bcm_pressure_gradie
! falkner_skan_map.py): adverse -a tanh(-u/b), favourable c (exp(u/d) - 1), blended over eps; u clipped
! to +-uclip before the exponential (u is o(1e3) outside the boundary layer).
! one parameter per line (tapenade wraps long declarations mid-token)
    real(kind=realtype), parameter :: pgmapa=0.06913_realtype
    real(kind=realtype), parameter :: pgmapb=0.03255_realtype
    real(kind=realtype), parameter :: pgmapc=0.09912_realtype
    real(kind=realtype), parameter :: pgmapd=0.04229_realtype
    real(kind=realtype), parameter :: pgmapeps=0.003_realtype
    real(kind=realtype), parameter :: pguclip=0.2_realtype
    real(kind=realtype), parameter :: pguclipneg=-0.2_realtype
    real(kind=realtype), parameter :: xminn=1.e-10_realtype
    intrinsic mod
    intrinsic sqrt
    intrinsic exp
    intrinsic min
    intrinsic max
    intrinsic tanh
    intrinsic log
    real(kind=realtype) :: y1
    real(kind=realtype) :: x1
    real(kind=realtype) :: min1
    real(kind=realtype) :: max1
    real(kind=realtype) :: max2
    real(kind=realtype) :: max3
    real(kind=realtype) :: max4
! set model constants
    cv13 = rsacv1**3
    kar2inv = one/rsak**2
    cw36 = rsacw3**6
    cb3inv = one/rsacb3
! determine the non-dimensional wheel speed of this block.
    omegax = timeref*sections(sectionid)%rotrate(1)
    omegay = timeref*sections(sectionid)%rotrate(2)
    omegaz = timeref*sections(sectionid)%rotrate(3)
! create switches to production term depending on the variable that
! should be used
    if (turbprod .eq. katolaunder) then
      print*, 'katolaunder production term not supported for sa'
      stop
    else
!$ad ii-loop
      do ii=0,nx*ny*nz-1
        i = mod(ii, nx) + 2
        j = mod(ii/nx, ny) + 2
        k = ii/(nx*ny) + 2
! compute the gradient of u in the cell center. use is made
! of the fact that the surrounding normals sum up to zero,
! such that the cell i,j,k does not give a contribution.
! the gradient is scaled by the factor 2*vol.
        uux = w(i+1, j, k, ivx)*si(i, j, k, 1) - w(i-1, j, k, ivx)*si(i-&
&         1, j, k, 1) + w(i, j+1, k, ivx)*sj(i, j, k, 1) - w(i, j-1, k, &
&         ivx)*sj(i, j-1, k, 1) + w(i, j, k+1, ivx)*sk(i, j, k, 1) - w(i&
&         , j, k-1, ivx)*sk(i, j, k-1, 1)
        uuy = w(i+1, j, k, ivx)*si(i, j, k, 2) - w(i-1, j, k, ivx)*si(i-&
&         1, j, k, 2) + w(i, j+1, k, ivx)*sj(i, j, k, 2) - w(i, j-1, k, &
&         ivx)*sj(i, j-1, k, 2) + w(i, j, k+1, ivx)*sk(i, j, k, 2) - w(i&
&         , j, k-1, ivx)*sk(i, j, k-1, 2)
        uuz = w(i+1, j, k, ivx)*si(i, j, k, 3) - w(i-1, j, k, ivx)*si(i-&
&         1, j, k, 3) + w(i, j+1, k, ivx)*sj(i, j, k, 3) - w(i, j-1, k, &
&         ivx)*sj(i, j-1, k, 3) + w(i, j, k+1, ivx)*sk(i, j, k, 3) - w(i&
&         , j, k-1, ivx)*sk(i, j, k-1, 3)
! idem for the gradient of v.
        vvx = w(i+1, j, k, ivy)*si(i, j, k, 1) - w(i-1, j, k, ivy)*si(i-&
&         1, j, k, 1) + w(i, j+1, k, ivy)*sj(i, j, k, 1) - w(i, j-1, k, &
&         ivy)*sj(i, j-1, k, 1) + w(i, j, k+1, ivy)*sk(i, j, k, 1) - w(i&
&         , j, k-1, ivy)*sk(i, j, k-1, 1)
        vvy = w(i+1, j, k, ivy)*si(i, j, k, 2) - w(i-1, j, k, ivy)*si(i-&
&         1, j, k, 2) + w(i, j+1, k, ivy)*sj(i, j, k, 2) - w(i, j-1, k, &
&         ivy)*sj(i, j-1, k, 2) + w(i, j, k+1, ivy)*sk(i, j, k, 2) - w(i&
&         , j, k-1, ivy)*sk(i, j, k-1, 2)
        vvz = w(i+1, j, k, ivy)*si(i, j, k, 3) - w(i-1, j, k, ivy)*si(i-&
&         1, j, k, 3) + w(i, j+1, k, ivy)*sj(i, j, k, 3) - w(i, j-1, k, &
&         ivy)*sj(i, j-1, k, 3) + w(i, j, k+1, ivy)*sk(i, j, k, 3) - w(i&
&         , j, k-1, ivy)*sk(i, j, k-1, 3)
! and for the gradient of w.
        wwx = w(i+1, j, k, ivz)*si(i, j, k, 1) - w(i-1, j, k, ivz)*si(i-&
&         1, j, k, 1) + w(i, j+1, k, ivz)*sj(i, j, k, 1) - w(i, j-1, k, &
&         ivz)*sj(i, j-1, k, 1) + w(i, j, k+1, ivz)*sk(i, j, k, 1) - w(i&
&         , j, k-1, ivz)*sk(i, j, k-1, 1)
        wwy = w(i+1, j, k, ivz)*si(i, j, k, 2) - w(i-1, j, k, ivz)*si(i-&
&         1, j, k, 2) + w(i, j+1, k, ivz)*sj(i, j, k, 2) - w(i, j-1, k, &
&         ivz)*sj(i, j-1, k, 2) + w(i, j, k+1, ivz)*sk(i, j, k, 2) - w(i&
&         , j, k-1, ivz)*sk(i, j, k-1, 2)
        wwz = w(i+1, j, k, ivz)*si(i, j, k, 3) - w(i-1, j, k, ivz)*si(i-&
&         1, j, k, 3) + w(i, j+1, k, ivz)*sj(i, j, k, 3) - w(i, j-1, k, &
&         ivz)*sj(i, j-1, k, 3) + w(i, j, k+1, ivz)*sk(i, j, k, 3) - w(i&
&         , j, k-1, ivz)*sk(i, j, k-1, 3)
! compute the components of the stress tensor.
! the combination of the current scaling of the velocity
! gradients (2*vol) and the definition of the stress tensor,
! leads to the factor 1/(4*vol).
        fact = fourth/vol(i, j, k)
        if (turbprod .eq. strain) then
          sxx = two*fact*uux
          syy = two*fact*vvy
          szz = two*fact*wwz
          sxy = fact*(uuy+vvx)
          sxz = fact*(uuz+wwx)
          syz = fact*(vvz+wwy)
! compute 2/3 * divergence of velocity squared
          div2 = f23*(sxx+syy+szz)**2
! compute strain production term
          strainmag2 = two*(sxy**2+sxz**2+syz**2) + sxx**2 + syy**2 + &
&           szz**2
          strainprod = two*strainmag2 - div2
          ss = sqrt(strainprod)
        else if (turbprod .eq. vorticity) then
! compute the three components of the vorticity vector.
! substract the part coming from the rotating frame.
          vortx = two*fact*(wwy-vvz) - two*omegax
          vorty = two*fact*(uuz-wwx) - two*omegay
          vortz = two*fact*(vvx-uuy) - two*omegaz
! compute the vorticity production term
          vortprod = vortx**2 + vorty**2 + vortz**2
! first take the square root of the production term to
! obtain the correct production term for spalart-allmaras.
! we do this to avoid if statements.
          ss = sqrt(vortprod)
        end if
! compute the laminar kinematic viscosity, the inverse of
! wall distance squared, the ratio chi (ratio of nutilde
! and nu) and the functions fv1 and fv2. the latter corrects
! the production term near a viscous wall.
        nu = rlv(i, j, k)/w(i, j, k, irho)
        dist2inv = one/d2wall(i, j, k)**2
        chi = w(i, j, k, itu1)/nu
        chi2 = chi*chi
        chi3 = chi*chi2
        fv1 = chi3/(chi3+cv13)
        fv2 = one - chi/(one+chi*fv1)
! the function ft2, which is designed to keep a laminar
! solution laminar. when running in fully turbulent mode
! this function should be set to 0.0.
        if (useft2sa) then
          ft2 = rsact3*exp(-(rsact4*chi2))
        else
          ft2 = zero
        end if
! correct the production term to account for the influence
! of the wall.
        sst = ss + w(i, j, k, itu1)*fv2*kar2inv*dist2inv
! add rotation term (userotationsa defined in inputparams.f90)
        if (userotationsa) then
          y1 = sqrt(two*strainmag2)
          if (zero .gt. y1) then
            min1 = y1
          else
            min1 = zero
          end if
          sst = sst + rsacrot*min1
        end if
        if (sst .lt. xminn) then
          sst = xminn
        else
          sst = sst
        end if
! compute the function fw. the argument rr is cut off at 10
! to avoid numerical problems. this is ok, because the
! asymptotical value of fw is then already reached.
        rr = w(i, j, k, itu1)*kar2inv*dist2inv/sst
        if (rr .gt. 10.0_realtype) then
          rr = 10.0_realtype
        else
          rr = rr
        end if
        gg = rr + rsacw2*(rr**6-rr)
        gg6 = gg**6
        termfw = ((one+cw36)/(gg6+cw36))**sixth
        fwsa = gg*termfw
        ttgamma = one
        if (use_sabcm) then
! compute the three components of the vorticity vector.
! substract the part coming from the rotating frame.
          vortx = two*fact*(wwy-vvz) - two*omegax
          vorty = two*fact*(uuz-wwx) - two*omegay
          vortz = two*fact*(vvx-uuy) - two*omegaz
! compute the vorticity production term
          vortprod = vortx**2 + vorty**2 + vortz**2
! first take the square root of the production term to
! obtain the correct production term for spalart-allmaras.
! we do this to avoid if statements.
          sqrtvort = sqrt(vortprod)
! tterm2 (small values ~0.01)
          tterm2 = fv1*chi/sabcm_const2
! re_theta critical
          rethetabase = 803.73_realtype*(sabcm_tu+0.6067_realtype)**(-&
&           1.027_realtype)
! pressure-gradient sensor (menter 2015 lambda_thetal with the
! wall normal n = nwall, langtry f(lambda) as in the sa-gamma-retheta
! model). off => flam = 1 and rethetacrit = rethetabase exactly.
          flam = one
          laml = zero
          if (sabcm_pg) then
            nwx = nwall(1, i, j, k)
            nwy = nwall(2, i, j, k)
            nwz = nwall(3, i, j, k)
! n . grad(u) . n ; true gradient = two*fact*(uu.), fact = fourth/vol
            snn = two*fact*(nwx*(nwx*uux+nwy*uuy+nwz*uuz)+nwy*(nwx*vvx+&
&             nwy*vvy+nwz*vvz)+nwz*(nwx*wwx+nwy*wwy+nwz*wwz))
! no reynolds factor: nu = rlv/rho is non-dimensional with
! l_ref = 1 m, same convention as re_vorty below.
            if (sabcm_pg_sensor .ge. 2) then
! wall-pressure-gradient sensors: du_e/ds with u_e from bernoulli and the
! local pressure (p ~ p_wall across the layer), s = velocity direction, p from w (constant cp).
! k = (thetahat/eta*)^2 of the blasius profile = 0.05064: lambda_theta of falkner-skan to +-5 %,
! no offset (u_e' = 0 for blasius), no gain. independent of the velocity profile => no
! transition/sensor feedback (docs/studies/22_bcm_pressure_gradient/falkner_skan_psensor.py).
              gm1 = gammaconstant - one
              pc = gm1*(w(i, j, k, irhoe)-half*w(i, j, k, irho)*(w(i, j&
&               , k, ivx)**2+w(i, j, k, ivy)**2+w(i, j, k, ivz)**2))
              pip = gm1*(w(i+1, j, k, irhoe)-half*w(i+1, j, k, irho)*(w(&
&               i+1, j, k, ivx)**2+w(i+1, j, k, ivy)**2+w(i+1, j, k, ivz&
&               )**2))
              pim = gm1*(w(i-1, j, k, irhoe)-half*w(i-1, j, k, irho)*(w(&
&               i-1, j, k, ivx)**2+w(i-1, j, k, ivy)**2+w(i-1, j, k, ivz&
&               )**2))
              pjp = gm1*(w(i, j+1, k, irhoe)-half*w(i, j+1, k, irho)*(w(&
&               i, j+1, k, ivx)**2+w(i, j+1, k, ivy)**2+w(i, j+1, k, ivz&
&               )**2))
              pjm = gm1*(w(i, j-1, k, irhoe)-half*w(i, j-1, k, irho)*(w(&
&               i, j-1, k, ivx)**2+w(i, j-1, k, ivy)**2+w(i, j-1, k, ivz&
&               )**2))
              pkp = gm1*(w(i, j, k+1, irhoe)-half*w(i, j, k+1, irho)*(w(&
&               i, j, k+1, ivx)**2+w(i, j, k+1, ivy)**2+w(i, j, k+1, ivz&
&               )**2))
              pkm = gm1*(w(i, j, k-1, irhoe)-half*w(i, j, k-1, irho)*(w(&
&               i, j, k-1, ivx)**2+w(i, j, k-1, ivy)**2+w(i, j, k-1, ivz&
&               )**2))
              ppx = pip*si(i, j, k, 1) - pim*si(i-1, j, k, 1) + pjp*sj(i&
&               , j, k, 1) - pjm*sj(i, j-1, k, 1) + pkp*sk(i, j, k, 1) -&
&               pkm*sk(i, j, k-1, 1)
              ppy = pip*si(i, j, k, 2) - pim*si(i-1, j, k, 2) + pjp*sj(i&
&               , j, k, 2) - pjm*sj(i, j-1, k, 2) + pkp*sk(i, j, k, 2) -&
&               pkm*sk(i, j, k-1, 2)
              ppz = pip*si(i, j, k, 3) - pim*si(i-1, j, k, 3) + pjp*sj(i&
&               , j, k, 3) - pjm*sj(i, j-1, k, 3) + pkp*sk(i, j, k, 3) -&
&               pkm*sk(i, j, k-1, 3)
              if (sabcm_pg_sdir .eq. 2) then
! edge-streamline direction = wall tangent oriented by the free stream (never
! reversed inside separation bubbles): t = e_inf - (e_inf.n) n, s = t/max(|t|, tmin)
                vdn = veldirfreestream(1)*nwx + veldirfreestream(2)*nwy &
&                 + veldirfreestream(3)*nwz
                tx = veldirfreestream(1) - vdn*nwx
                ty = veldirfreestream(2) - vdn*nwy
                tz = veldirfreestream(3) - vdn*nwz
                tmag = sqrt(tx**2 + ty**2 + tz**2)
                tmagc = smoothminmax(tmag, pgtangmin, sabcm_pg_p)
                uxh = tx/tmagc
                uyh = ty/tmagc
                uzh = tz/tmagc
              else
                velmagpg = sqrt(w(i, j, k, ivx)**2 + w(i, j, k, ivy)**2 &
&                 + w(i, j, k, ivz)**2)
                if (velmagpg .lt. xminn) then
                  max1 = xminn
                else
                  max1 = velmagpg
                end if
                uxh = w(i, j, k, ivx)/max1
                if (velmagpg .lt. xminn) then
                  max2 = xminn
                else
                  max2 = velmagpg
                end if
                uyh = w(i, j, k, ivy)/max2
                if (velmagpg .lt. xminn) then
                  max3 = xminn
                else
                  max3 = velmagpg
                end if
                uzh = w(i, j, k, ivz)/max3
              end if
              dpds = two*fact*(uxh*ppx+uyh*ppy+uzh*ppz)
              ue2 = uinf**2 + two*(pinfcorr-pc)/rhoinf
              ue2min = (pgueminfrac*uinf)**2
              if (ue2 .lt. ue2min) then
                ue2c = ue2min
              else
                ue2c = ue2
              end if
              ue = sqrt(ue2c)
              dueds = -(dpds/(rhoinf*ue))
              if (sabcm_pg_sensor .eq. 3) then
! sensor 3: reference-model definition, theta = re_theta_c(tu)*nu/u_e (p&z eqs. 10-14:
! theta_t = re_theta_t nu/u) -> lambda = theta^2 u_e'/nu, uniform across the layer.
                thetam = rethetabase*nu/ue
                laml = thetam**2/nu*dueds
              else
! sensor 2: physical theta ~ d at the re_v peak, k = (thetahat/eta*)^2 blasius
                laml = sabcm_pg_k*(d2wall(i, j, k)**2/nu)*dueds
              end if
            else
              laml = -(sabcm_pg_coef*(d2wall(i, j, k)**2/nu)*snn) + &
&               sabcm_pg_off
            end if
! smooth clip of gain*laml to [-lammax, lammax] (distinct
! targets, not in place: keeps the fast-reverse ad exact).
! module variables are copied to locals before being passed to the
! differentiated helpers (tapenade otherwise emits a seed for them).
            mlammax = -sabcm_pg_lammax
            plammax = sabcm_pg_lammax
            mp = -sabcm_pg_p
            if (sabcm_pg_sensor .ge. 2) then
! already lambda_theta (no gain/map)
              lammapped = laml
            else if (sabcm_pg_map .eq. 2) then
! exact similarity map (no free gain): clip u, two analytic branches, smooth blend
              umaplo = smoothminmax(laml, pguclipneg, sabcm_pg_p)
              umap = smoothminmax(umaplo, pguclip, mp)
              vadv = pgmapa*tanh(umap/pgmapb)
              vfav = pgmapc*(exp(umap/pgmapd)-one)
              wmap = half*(one+tanh(umap/pgmapeps))
              lammapped = (one-wmap)*vadv + wmap*vfav
            else
              lammapped = sabcm_pg_gain*laml
            end if
            lamlo = smoothminmax(lammapped, mlammax, sabcm_pg_p)
            lam = smoothminmax(lamlo, plammax, mp)
            flam = bcmflambda(sabcm_tu, lam, sabcm_pg_p)
          end if
! distinct target (never rethetacrit = rethetacrit*flam): the fast-reverse ad has no
! push/pop stack, an in-place update would use the overwritten value in flamd.
! flam = one when sabcm_pg is off: the product is exact, pg-off stays bit-identical.
          rethetacrit = rethetabase*flam
! re_theta actual
          re_vorty = sqrtvort*w(i, j, k, irho)/rlv(i, j, k)*d2wall(i, j&
&           , k)**2
          re_theta = re_vorty/2.193_realtype
! tterm1 (can be huge ~1e5)
          tterm1 = (re_theta-rethetacrit)/(rethetacrit*sabcm_const1)
          if (sabcm_exp) then
            if (tterm1 .lt. zero) then
              tterm1 = zero
            else
              tterm1 = tterm1
            end if
            if (tterm2 .lt. zero) then
              max4 = zero
            else
              max4 = tterm2
            end if
            arg_gamma = sqrt(tterm1) + sqrt(max4)
            ttgamma = one - exp(-arg_gamma)
            if (ttgamma .lt. zero) then
              x1 = zero
            else
              x1 = ttgamma
            end if
            if (x1 .gt. one) then
              ttgamma = one
            else
              ttgamma = x1
            end if
          else
! differentiable reformulation: ks-smoothed max in term1, tanh intermittency
            stransition = sabcm_maxsmooth*tterm1
            if (stransition .lt. xminn) then
              k_max = xminn
            else
              k_max = stransition
            end if
            tterm1 = (k_max+log(exp(stransition-k_max)+exp(-k_max)))/&
&             sabcm_maxsmooth
! current tanh-based formula
            arg_tanh = (tterm1+tterm2-sabcm_s0_tanh)/sabcm_fsmooth
            ttgamma = 0.5_realtype*(1.0_realtype+tanh(arg_tanh))
          end if
          tgamma(i, j, k) = ttgamma
          bcmlambda(i, j, k) = laml
          bcmflam(i, j, k) = flam
          ft2 = zero
        end if
! compute the source term; some terms are saved for the
! linearization. the source term is stored in dvt.
        if (approxsa) then
          term1 = zero
        else
          term1 = ttgamma*rsacb1*(one-ft2)*ss
        end if
        term2 = dist2inv*(kar2inv*ttgamma*rsacb1*((one-ft2)*fv2+ft2)-&
&         rsacw1*fwsa)
        scratch(i, j, k, idvt) = (term1+term2*w(i, j, k, itu1))*w(i, j, &
&         k, itu1)
      end do
    end if
  end subroutine sasource

!  differentiation of saviscous in reverse (adjoint) mode (with options noisize i4 dr8 r8):
!   gradient     of useful results: *w *rlv *scratch
!   with respect to varying inputs: *w *rlv *scratch
!   rw status of diff variables: *w:incr *rlv:incr *scratch:in-out
!   plus diff mem management of: w:in rlv:in scratch:in
  subroutine saviscous_fast_b()
!
!  viscous term.
!  determine the viscous contribution to the residual
!  for all internal cells of the block.
    use blockpointers
    use paramturb
    implicit none
! local variables.
    integer(kind=inttype) :: i, j, k, nn, ii
    real(kind=realtype) :: nu
    real(kind=realtype) :: nud
    real(kind=realtype) :: fv1, fv2, ft2
    real(kind=realtype) :: voli, volmi, volpi, xm, ym, zm, xp, yp, zp
    real(kind=realtype) :: xa, ya, za, ttm, ttp, cnud, cam, cap
    real(kind=realtype) :: cnudd, camd, capd
    real(kind=realtype) :: nutm, nutp, num, nup, cdm, cdp
    real(kind=realtype) :: nutmd, nutpd, numd, nupd, cdmd, cdpd
    real(kind=realtype) :: c1m, c1p, c10, b1, c1, d1, qs
    real(kind=realtype) :: c1md, c1pd, c10d
    intrinsic mod
    intrinsic max
    real(kind=realtype) :: temp
    real(kind=realtype) :: temp0
    real(kind=realtype) :: tempd
    real(kind=realtype) :: tempd0
    integer :: branch
! set model constants
    cb3inv = one/rsacb3
!$bwd-of ii-loop 
    do ii=0,nx*ny*nz-1
      i = mod(ii, nx) + 2
      j = mod(ii/nx, ny) + 2
      k = ii/(nx*ny) + 2
! compute the metrics in xi-direction, i.e. along the
! line i = constant.
      voli = one/vol(i, j, k)
      volmi = two/(vol(i, j, k)+vol(i-1, j, k))
      volpi = two/(vol(i, j, k)+vol(i+1, j, k))
      xm = si(i-1, j, k, 1)*volmi
      ym = si(i-1, j, k, 2)*volmi
      zm = si(i-1, j, k, 3)*volmi
      xp = si(i, j, k, 1)*volpi
      yp = si(i, j, k, 2)*volpi
      zp = si(i, j, k, 3)*volpi
      xa = half*(si(i, j, k, 1)+si(i-1, j, k, 1))*voli
      ya = half*(si(i, j, k, 2)+si(i-1, j, k, 2))*voli
      za = half*(si(i, j, k, 3)+si(i-1, j, k, 3))*voli
      ttm = xm*xa + ym*ya + zm*za
      ttp = xp*xa + yp*ya + zp*za
! computation of the viscous terms in xi-direction; note
! that cross-derivatives are neglected, i.e. the mesh is
! assumed to be orthogonal.
! furthermore, the grad(nu)**2 has been rewritten as
! div(nu grad(nu)) - nu div(grad nu) to enhance stability.
! the second derivative in xi-direction is constructed as
! the central difference of the first order derivatives, i.e.
! d^2/dxi^2 = d/dxi (d/dxi i+1/2 - d/dxi i-1/2).
! in this way the metric can be taken into account.
! compute the diffusion coefficients multiplying the nodes
! i+1, i and i-1 in the second derivative. make sure that
! these coefficients are nonnegative.
      cnud = -(rsacb2*w(i, j, k, itu1)*cb3inv)
      cam = ttm*cnud
      cap = ttp*cnud
      nutm = half*(w(i-1, j, k, itu1)+w(i, j, k, itu1))
      nutp = half*(w(i+1, j, k, itu1)+w(i, j, k, itu1))
      nu = rlv(i, j, k)/w(i, j, k, irho)
      num = half*(rlv(i-1, j, k)/w(i-1, j, k, irho)+nu)
      nup = half*(rlv(i+1, j, k)/w(i+1, j, k, irho)+nu)
      cdm = (num+(one+rsacb2)*nutm)*ttm*cb3inv
      cdp = (nup+(one+rsacb2)*nutp)*ttp*cb3inv
      if (cdm + cam .lt. zero) then
        c1m = zero
myIntPtr = myIntPtr + 1
 myIntStack(myIntPtr) = 0
      else
        c1m = cdm + cam
myIntPtr = myIntPtr + 1
 myIntStack(myIntPtr) = 1
      end if
      if (cdp + cap .lt. zero) then
        c1p = zero
myIntPtr = myIntPtr + 1
 myIntStack(myIntPtr) = 0
      else
        c1p = cdp + cap
myIntPtr = myIntPtr + 1
 myIntStack(myIntPtr) = 1
      end if
      c10 = c1m + c1p
! update the residual for this cell and store the possible
! coefficients for the matrix in b1, c1 and d1.
      c10d = -(w(i, j, k, itu1)*scratchd(i, j, k, idvt))
      c1md = w(i-1, j, k, itu1)*scratchd(i, j, k, idvt) + c10d
      wd(i-1, j, k, itu1) = wd(i-1, j, k, itu1) + c1m*scratchd(i, j, k, &
&       idvt)
      c1pd = w(i+1, j, k, itu1)*scratchd(i, j, k, idvt) + c10d
      wd(i+1, j, k, itu1) = wd(i+1, j, k, itu1) + c1p*scratchd(i, j, k, &
&       idvt)
      wd(i, j, k, itu1) = wd(i, j, k, itu1) - c10*scratchd(i, j, k, idvt&
&       )
branch = myIntStack(myIntPtr)
 myIntPtr = myIntPtr - 1
      if (branch .eq. 0) then
        cdpd = 0.0_8
        capd = 0.0_8
      else
        cdpd = c1pd
        capd = c1pd
      end if
branch = myIntStack(myIntPtr)
 myIntPtr = myIntPtr - 1
      if (branch .eq. 0) then
        cdmd = 0.0_8
        camd = 0.0_8
      else
        cdmd = c1md
        camd = c1md
      end if
      cnudd = ttp*capd + ttm*camd
      tempd = ttp*cb3inv*cdpd
      nupd = tempd
      nutpd = (one+rsacb2)*tempd
      tempd = ttm*cb3inv*cdmd
      numd = tempd
      nutmd = (one+rsacb2)*tempd
      temp0 = w(i+1, j, k, irho)
      tempd0 = half*nupd/temp0
      nud = half*nupd + half*numd
      rlvd(i+1, j, k) = rlvd(i+1, j, k) + tempd0
      wd(i+1, j, k, irho) = wd(i+1, j, k, irho) - rlv(i+1, j, k)*tempd0/&
&       temp0
      temp0 = w(i-1, j, k, irho)
      tempd0 = half*numd/temp0
      rlvd(i-1, j, k) = rlvd(i-1, j, k) + tempd0
      wd(i-1, j, k, irho) = wd(i-1, j, k, irho) - rlv(i-1, j, k)*tempd0/&
&       temp0
      temp0 = w(i, j, k, irho)
      rlvd(i, j, k) = rlvd(i, j, k) + nud/temp0
      wd(i, j, k, irho) = wd(i, j, k, irho) - rlv(i, j, k)*nud/temp0**2
      wd(i+1, j, k, itu1) = wd(i+1, j, k, itu1) + half*nutpd
      wd(i, j, k, itu1) = wd(i, j, k, itu1) + half*nutpd + half*nutmd - &
&       rsacb2*cb3inv*cnudd
      wd(i-1, j, k, itu1) = wd(i-1, j, k, itu1) + half*nutmd
    end do
!$bwd-of ii-loop 
    do ii=0,nx*ny*nz-1
      i = mod(ii, nx) + 2
      j = mod(ii/nx, ny) + 2
      k = ii/(nx*ny) + 2
! compute the metrics in eta-direction, i.e. along the
! line j = constant.
      voli = one/vol(i, j, k)
      volmi = two/(vol(i, j, k)+vol(i, j-1, k))
      volpi = two/(vol(i, j, k)+vol(i, j+1, k))
      xm = sj(i, j-1, k, 1)*volmi
      ym = sj(i, j-1, k, 2)*volmi
      zm = sj(i, j-1, k, 3)*volmi
      xp = sj(i, j, k, 1)*volpi
      yp = sj(i, j, k, 2)*volpi
      zp = sj(i, j, k, 3)*volpi
      xa = half*(sj(i, j, k, 1)+sj(i, j-1, k, 1))*voli
      ya = half*(sj(i, j, k, 2)+sj(i, j-1, k, 2))*voli
      za = half*(sj(i, j, k, 3)+sj(i, j-1, k, 3))*voli
      ttm = xm*xa + ym*ya + zm*za
      ttp = xp*xa + yp*ya + zp*za
! computation of the viscous terms in eta-direction; note
! that cross-derivatives are neglected, i.e. the mesh is
! assumed to be orthogonal.
! furthermore, the grad(nu)**2 has been rewritten as
! div(nu grad(nu)) - nu div(grad nu) to enhance stability.
! the second derivative in eta-direction is constructed as
! the central difference of the first order derivatives, i.e.
! d^2/deta^2 = d/deta (d/deta j+1/2 - d/deta j-1/2).
! in this way the metric can be taken into account.
! compute the diffusion coefficients multiplying the nodes
! j+1, j and j-1 in the second derivative. make sure that
! these coefficients are nonnegative.
      cnud = -(rsacb2*w(i, j, k, itu1)*cb3inv)
      cam = ttm*cnud
      cap = ttp*cnud
      nutm = half*(w(i, j-1, k, itu1)+w(i, j, k, itu1))
      nutp = half*(w(i, j+1, k, itu1)+w(i, j, k, itu1))
      nu = rlv(i, j, k)/w(i, j, k, irho)
      num = half*(rlv(i, j-1, k)/w(i, j-1, k, irho)+nu)
      nup = half*(rlv(i, j+1, k)/w(i, j+1, k, irho)+nu)
      cdm = (num+(one+rsacb2)*nutm)*ttm*cb3inv
      cdp = (nup+(one+rsacb2)*nutp)*ttp*cb3inv
      if (cdm + cam .lt. zero) then
        c1m = zero
myIntPtr = myIntPtr + 1
 myIntStack(myIntPtr) = 0
      else
        c1m = cdm + cam
myIntPtr = myIntPtr + 1
 myIntStack(myIntPtr) = 1
      end if
      if (cdp + cap .lt. zero) then
        c1p = zero
myIntPtr = myIntPtr + 1
 myIntStack(myIntPtr) = 0
      else
        c1p = cdp + cap
myIntPtr = myIntPtr + 1
 myIntStack(myIntPtr) = 1
      end if
      c10 = c1m + c1p
! update the residual for this cell and store the possible
! coefficients for the matrix in b1, c1 and d1.
      c10d = -(w(i, j, k, itu1)*scratchd(i, j, k, idvt))
      c1md = w(i, j-1, k, itu1)*scratchd(i, j, k, idvt) + c10d
      wd(i, j-1, k, itu1) = wd(i, j-1, k, itu1) + c1m*scratchd(i, j, k, &
&       idvt)
      c1pd = w(i, j+1, k, itu1)*scratchd(i, j, k, idvt) + c10d
      wd(i, j+1, k, itu1) = wd(i, j+1, k, itu1) + c1p*scratchd(i, j, k, &
&       idvt)
      wd(i, j, k, itu1) = wd(i, j, k, itu1) - c10*scratchd(i, j, k, idvt&
&       )
branch = myIntStack(myIntPtr)
 myIntPtr = myIntPtr - 1
      if (branch .eq. 0) then
        cdpd = 0.0_8
        capd = 0.0_8
      else
        cdpd = c1pd
        capd = c1pd
      end if
branch = myIntStack(myIntPtr)
 myIntPtr = myIntPtr - 1
      if (branch .eq. 0) then
        cdmd = 0.0_8
        camd = 0.0_8
      else
        cdmd = c1md
        camd = c1md
      end if
      cnudd = ttp*capd + ttm*camd
      tempd = ttp*cb3inv*cdpd
      nupd = tempd
      nutpd = (one+rsacb2)*tempd
      tempd = ttm*cb3inv*cdmd
      numd = tempd
      nutmd = (one+rsacb2)*tempd
      temp0 = w(i, j+1, k, irho)
      tempd0 = half*nupd/temp0
      nud = half*nupd + half*numd
      rlvd(i, j+1, k) = rlvd(i, j+1, k) + tempd0
      wd(i, j+1, k, irho) = wd(i, j+1, k, irho) - rlv(i, j+1, k)*tempd0/&
&       temp0
      temp0 = w(i, j-1, k, irho)
      tempd0 = half*numd/temp0
      rlvd(i, j-1, k) = rlvd(i, j-1, k) + tempd0
      wd(i, j-1, k, irho) = wd(i, j-1, k, irho) - rlv(i, j-1, k)*tempd0/&
&       temp0
      temp0 = w(i, j, k, irho)
      rlvd(i, j, k) = rlvd(i, j, k) + nud/temp0
      wd(i, j, k, irho) = wd(i, j, k, irho) - rlv(i, j, k)*nud/temp0**2
      wd(i, j+1, k, itu1) = wd(i, j+1, k, itu1) + half*nutpd
      wd(i, j, k, itu1) = wd(i, j, k, itu1) + half*nutpd + half*nutmd - &
&       rsacb2*cb3inv*cnudd
      wd(i, j-1, k, itu1) = wd(i, j-1, k, itu1) + half*nutmd
    end do
!$bwd-of ii-loop 
    do ii=0,nx*ny*nz-1
      i = mod(ii, nx) + 2
      j = mod(ii/nx, ny) + 2
      k = ii/(nx*ny) + 2
! compute the metrics in zeta-direction, i.e. along the
! line k = constant.
      voli = one/vol(i, j, k)
      volmi = two/(vol(i, j, k)+vol(i, j, k-1))
      volpi = two/(vol(i, j, k)+vol(i, j, k+1))
      xm = sk(i, j, k-1, 1)*volmi
      ym = sk(i, j, k-1, 2)*volmi
      zm = sk(i, j, k-1, 3)*volmi
      xp = sk(i, j, k, 1)*volpi
      yp = sk(i, j, k, 2)*volpi
      zp = sk(i, j, k, 3)*volpi
      xa = half*(sk(i, j, k, 1)+sk(i, j, k-1, 1))*voli
      ya = half*(sk(i, j, k, 2)+sk(i, j, k-1, 2))*voli
      za = half*(sk(i, j, k, 3)+sk(i, j, k-1, 3))*voli
      ttm = xm*xa + ym*ya + zm*za
      ttp = xp*xa + yp*ya + zp*za
! ttm and ttp ~ 1/deltax^2
! computation of the viscous terms in zeta-direction; note
! that cross-derivatives are neglected, i.e. the mesh is
! assumed to be orthogonal.
! furthermore, the grad(nu)**2 has been rewritten as
! div(nu grad(nu)) - nu div(grad nu) to enhance stability.
! the second derivative in zeta-direction is constructed as
! the central difference of the first order derivatives, i.e.
! d^2/dzeta^2 = d/dzeta (d/dzeta k+1/2 - d/dzeta k-1/2).
! in this way the metric can be taken into account.
! compute the diffusion coefficients multiplying the nodes
! k+1, k and k-1 in the second derivative. make sure that
! these coefficients are nonnegative.
      cnud = -(rsacb2*w(i, j, k, itu1)*cb3inv)
      cam = ttm*cnud
      cap = ttp*cnud
! compute nutilde at the faces
      nutm = half*(w(i, j, k-1, itu1)+w(i, j, k, itu1))
      nutp = half*(w(i, j, k+1, itu1)+w(i, j, k, itu1))
! compute nu at the faces
      nu = rlv(i, j, k)/w(i, j, k, irho)
      num = half*(rlv(i, j, k-1)/w(i, j, k-1, irho)+nu)
      nup = half*(rlv(i, j, k+1)/w(i, j, k+1, irho)+nu)
      cdm = (num+(one+rsacb2)*nutm)*ttm*cb3inv
      cdp = (nup+(one+rsacb2)*nutp)*ttp*cb3inv
      if (cdm + cam .lt. zero) then
        c1m = zero
myIntPtr = myIntPtr + 1
 myIntStack(myIntPtr) = 0
      else
        c1m = cdm + cam
myIntPtr = myIntPtr + 1
 myIntStack(myIntPtr) = 1
      end if
      if (cdp + cap .lt. zero) then
        c1p = zero
myIntPtr = myIntPtr + 1
 myIntStack(myIntPtr) = 0
      else
        c1p = cdp + cap
myIntPtr = myIntPtr + 1
 myIntStack(myIntPtr) = 1
      end if
      c10 = c1m + c1p
! update the residual for this cell and store the possible
! coefficients for the matrix in b1, c1 and d1.
      c10d = -(w(i, j, k, itu1)*scratchd(i, j, k, idvt))
      c1md = w(i, j, k-1, itu1)*scratchd(i, j, k, idvt) + c10d
      wd(i, j, k-1, itu1) = wd(i, j, k-1, itu1) + c1m*scratchd(i, j, k, &
&       idvt)
      c1pd = w(i, j, k+1, itu1)*scratchd(i, j, k, idvt) + c10d
      wd(i, j, k+1, itu1) = wd(i, j, k+1, itu1) + c1p*scratchd(i, j, k, &
&       idvt)
      wd(i, j, k, itu1) = wd(i, j, k, itu1) - c10*scratchd(i, j, k, idvt&
&       )
branch = myIntStack(myIntPtr)
 myIntPtr = myIntPtr - 1
      if (branch .eq. 0) then
        cdpd = 0.0_8
        capd = 0.0_8
      else
        cdpd = c1pd
        capd = c1pd
      end if
branch = myIntStack(myIntPtr)
 myIntPtr = myIntPtr - 1
      if (branch .eq. 0) then
        cdmd = 0.0_8
        camd = 0.0_8
      else
        cdmd = c1md
        camd = c1md
      end if
      cnudd = ttp*capd + ttm*camd
      tempd = ttp*cb3inv*cdpd
      nupd = tempd
      nutpd = (one+rsacb2)*tempd
      tempd = ttm*cb3inv*cdmd
      numd = tempd
      nutmd = (one+rsacb2)*tempd
      temp0 = w(i, j, k+1, irho)
      tempd0 = half*nupd/temp0
      nud = half*nupd + half*numd
      rlvd(i, j, k+1) = rlvd(i, j, k+1) + tempd0
      wd(i, j, k+1, irho) = wd(i, j, k+1, irho) - rlv(i, j, k+1)*tempd0/&
&       temp0
      temp = w(i, j, k-1, irho)
      tempd = half*numd/temp
      rlvd(i, j, k-1) = rlvd(i, j, k-1) + tempd
      wd(i, j, k-1, irho) = wd(i, j, k-1, irho) - rlv(i, j, k-1)*tempd/&
&       temp
      temp = w(i, j, k, irho)
      rlvd(i, j, k) = rlvd(i, j, k) + nud/temp
      wd(i, j, k, irho) = wd(i, j, k, irho) - rlv(i, j, k)*nud/temp**2
      wd(i, j, k+1, itu1) = wd(i, j, k+1, itu1) + half*nutpd
      wd(i, j, k, itu1) = wd(i, j, k, itu1) + half*nutpd + half*nutmd - &
&       rsacb2*cb3inv*cnudd
      wd(i, j, k-1, itu1) = wd(i, j, k-1, itu1) + half*nutmd
    end do
  end subroutine saviscous_fast_b

  subroutine saviscous()
!
!  viscous term.
!  determine the viscous contribution to the residual
!  for all internal cells of the block.
    use blockpointers
    use paramturb
    implicit none
! local variables.
    integer(kind=inttype) :: i, j, k, nn, ii
    real(kind=realtype) :: nu
    real(kind=realtype) :: fv1, fv2, ft2
    real(kind=realtype) :: voli, volmi, volpi, xm, ym, zm, xp, yp, zp
    real(kind=realtype) :: xa, ya, za, ttm, ttp, cnud, cam, cap
    real(kind=realtype) :: nutm, nutp, num, nup, cdm, cdp
    real(kind=realtype) :: c1m, c1p, c10, b1, c1, d1, qs
    intrinsic mod
    intrinsic max
! set model constants
    cv13 = rsacv1**3
    kar2inv = one/rsak**2
    cw36 = rsacw3**6
    cb3inv = one/rsacb3
!$ad ii-loop
!
!       viscous terms in k-direction.
!
    do ii=0,nx*ny*nz-1
      i = mod(ii, nx) + 2
      j = mod(ii/nx, ny) + 2
      k = ii/(nx*ny) + 2
! compute the metrics in zeta-direction, i.e. along the
! line k = constant.
      voli = one/vol(i, j, k)
      volmi = two/(vol(i, j, k)+vol(i, j, k-1))
      volpi = two/(vol(i, j, k)+vol(i, j, k+1))
      xm = sk(i, j, k-1, 1)*volmi
      ym = sk(i, j, k-1, 2)*volmi
      zm = sk(i, j, k-1, 3)*volmi
      xp = sk(i, j, k, 1)*volpi
      yp = sk(i, j, k, 2)*volpi
      zp = sk(i, j, k, 3)*volpi
      xa = half*(sk(i, j, k, 1)+sk(i, j, k-1, 1))*voli
      ya = half*(sk(i, j, k, 2)+sk(i, j, k-1, 2))*voli
      za = half*(sk(i, j, k, 3)+sk(i, j, k-1, 3))*voli
      ttm = xm*xa + ym*ya + zm*za
      ttp = xp*xa + yp*ya + zp*za
! ttm and ttp ~ 1/deltax^2
! computation of the viscous terms in zeta-direction; note
! that cross-derivatives are neglected, i.e. the mesh is
! assumed to be orthogonal.
! furthermore, the grad(nu)**2 has been rewritten as
! div(nu grad(nu)) - nu div(grad nu) to enhance stability.
! the second derivative in zeta-direction is constructed as
! the central difference of the first order derivatives, i.e.
! d^2/dzeta^2 = d/dzeta (d/dzeta k+1/2 - d/dzeta k-1/2).
! in this way the metric can be taken into account.
! compute the diffusion coefficients multiplying the nodes
! k+1, k and k-1 in the second derivative. make sure that
! these coefficients are nonnegative.
      cnud = -(rsacb2*w(i, j, k, itu1)*cb3inv)
      cam = ttm*cnud
      cap = ttp*cnud
! compute nutilde at the faces
      nutm = half*(w(i, j, k-1, itu1)+w(i, j, k, itu1))
      nutp = half*(w(i, j, k+1, itu1)+w(i, j, k, itu1))
! compute nu at the faces
      nu = rlv(i, j, k)/w(i, j, k, irho)
      num = half*(rlv(i, j, k-1)/w(i, j, k-1, irho)+nu)
      nup = half*(rlv(i, j, k+1)/w(i, j, k+1, irho)+nu)
      cdm = (num+(one+rsacb2)*nutm)*ttm*cb3inv
      cdp = (nup+(one+rsacb2)*nutp)*ttp*cb3inv
      if (cdm + cam .lt. zero) then
        c1m = zero
      else
        c1m = cdm + cam
      end if
      if (cdp + cap .lt. zero) then
        c1p = zero
      else
        c1p = cdp + cap
      end if
      c10 = c1m + c1p
! update the residual for this cell and store the possible
! coefficients for the matrix in b1, c1 and d1.
      scratch(i, j, k, idvt) = scratch(i, j, k, idvt) + c1m*w(i, j, k-1&
&       , itu1) - c10*w(i, j, k, itu1) + c1p*w(i, j, k+1, itu1)
    end do
!$ad ii-loop
!
!       viscous terms in j-direction.
!
    do ii=0,nx*ny*nz-1
      i = mod(ii, nx) + 2
      j = mod(ii/nx, ny) + 2
      k = ii/(nx*ny) + 2
! compute the metrics in eta-direction, i.e. along the
! line j = constant.
      voli = one/vol(i, j, k)
      volmi = two/(vol(i, j, k)+vol(i, j-1, k))
      volpi = two/(vol(i, j, k)+vol(i, j+1, k))
      xm = sj(i, j-1, k, 1)*volmi
      ym = sj(i, j-1, k, 2)*volmi
      zm = sj(i, j-1, k, 3)*volmi
      xp = sj(i, j, k, 1)*volpi
      yp = sj(i, j, k, 2)*volpi
      zp = sj(i, j, k, 3)*volpi
      xa = half*(sj(i, j, k, 1)+sj(i, j-1, k, 1))*voli
      ya = half*(sj(i, j, k, 2)+sj(i, j-1, k, 2))*voli
      za = half*(sj(i, j, k, 3)+sj(i, j-1, k, 3))*voli
      ttm = xm*xa + ym*ya + zm*za
      ttp = xp*xa + yp*ya + zp*za
! computation of the viscous terms in eta-direction; note
! that cross-derivatives are neglected, i.e. the mesh is
! assumed to be orthogonal.
! furthermore, the grad(nu)**2 has been rewritten as
! div(nu grad(nu)) - nu div(grad nu) to enhance stability.
! the second derivative in eta-direction is constructed as
! the central difference of the first order derivatives, i.e.
! d^2/deta^2 = d/deta (d/deta j+1/2 - d/deta j-1/2).
! in this way the metric can be taken into account.
! compute the diffusion coefficients multiplying the nodes
! j+1, j and j-1 in the second derivative. make sure that
! these coefficients are nonnegative.
      cnud = -(rsacb2*w(i, j, k, itu1)*cb3inv)
      cam = ttm*cnud
      cap = ttp*cnud
      nutm = half*(w(i, j-1, k, itu1)+w(i, j, k, itu1))
      nutp = half*(w(i, j+1, k, itu1)+w(i, j, k, itu1))
      nu = rlv(i, j, k)/w(i, j, k, irho)
      num = half*(rlv(i, j-1, k)/w(i, j-1, k, irho)+nu)
      nup = half*(rlv(i, j+1, k)/w(i, j+1, k, irho)+nu)
      cdm = (num+(one+rsacb2)*nutm)*ttm*cb3inv
      cdp = (nup+(one+rsacb2)*nutp)*ttp*cb3inv
      if (cdm + cam .lt. zero) then
        c1m = zero
      else
        c1m = cdm + cam
      end if
      if (cdp + cap .lt. zero) then
        c1p = zero
      else
        c1p = cdp + cap
      end if
      c10 = c1m + c1p
! update the residual for this cell and store the possible
! coefficients for the matrix in b1, c1 and d1.
      scratch(i, j, k, idvt) = scratch(i, j, k, idvt) + c1m*w(i, j-1, k&
&       , itu1) - c10*w(i, j, k, itu1) + c1p*w(i, j+1, k, itu1)
    end do
!$ad ii-loop
!
!       viscous terms in i-direction.
!
    do ii=0,nx*ny*nz-1
      i = mod(ii, nx) + 2
      j = mod(ii/nx, ny) + 2
      k = ii/(nx*ny) + 2
! compute the metrics in xi-direction, i.e. along the
! line i = constant.
      voli = one/vol(i, j, k)
      volmi = two/(vol(i, j, k)+vol(i-1, j, k))
      volpi = two/(vol(i, j, k)+vol(i+1, j, k))
      xm = si(i-1, j, k, 1)*volmi
      ym = si(i-1, j, k, 2)*volmi
      zm = si(i-1, j, k, 3)*volmi
      xp = si(i, j, k, 1)*volpi
      yp = si(i, j, k, 2)*volpi
      zp = si(i, j, k, 3)*volpi
      xa = half*(si(i, j, k, 1)+si(i-1, j, k, 1))*voli
      ya = half*(si(i, j, k, 2)+si(i-1, j, k, 2))*voli
      za = half*(si(i, j, k, 3)+si(i-1, j, k, 3))*voli
      ttm = xm*xa + ym*ya + zm*za
      ttp = xp*xa + yp*ya + zp*za
! computation of the viscous terms in xi-direction; note
! that cross-derivatives are neglected, i.e. the mesh is
! assumed to be orthogonal.
! furthermore, the grad(nu)**2 has been rewritten as
! div(nu grad(nu)) - nu div(grad nu) to enhance stability.
! the second derivative in xi-direction is constructed as
! the central difference of the first order derivatives, i.e.
! d^2/dxi^2 = d/dxi (d/dxi i+1/2 - d/dxi i-1/2).
! in this way the metric can be taken into account.
! compute the diffusion coefficients multiplying the nodes
! i+1, i and i-1 in the second derivative. make sure that
! these coefficients are nonnegative.
      cnud = -(rsacb2*w(i, j, k, itu1)*cb3inv)
      cam = ttm*cnud
      cap = ttp*cnud
      nutm = half*(w(i-1, j, k, itu1)+w(i, j, k, itu1))
      nutp = half*(w(i+1, j, k, itu1)+w(i, j, k, itu1))
      nu = rlv(i, j, k)/w(i, j, k, irho)
      num = half*(rlv(i-1, j, k)/w(i-1, j, k, irho)+nu)
      nup = half*(rlv(i+1, j, k)/w(i+1, j, k, irho)+nu)
      cdm = (num+(one+rsacb2)*nutm)*ttm*cb3inv
      cdp = (nup+(one+rsacb2)*nutp)*ttp*cb3inv
      if (cdm + cam .lt. zero) then
        c1m = zero
      else
        c1m = cdm + cam
      end if
      if (cdp + cap .lt. zero) then
        c1p = zero
      else
        c1p = cdp + cap
      end if
      c10 = c1m + c1p
! update the residual for this cell and store the possible
! coefficients for the matrix in b1, c1 and d1.
      scratch(i, j, k, idvt) = scratch(i, j, k, idvt) + c1m*w(i-1, j, k&
&       , itu1) - c10*w(i, j, k, itu1) + c1p*w(i+1, j, k, itu1)
    end do
  end subroutine saviscous

!  differentiation of saresscale in reverse (adjoint) mode (with options noisize i4 dr8 r8):
!   gradient     of useful results: *dw
!   with respect to varying inputs: *dw *scratch
!   rw status of diff variables: *dw:in-out *scratch:out
!   plus diff mem management of: dw:in scratch:in
  subroutine saresscale_fast_b()
!
!  multiply the residual by the volume and store this in dw; this
! * is done for monitoring reasons only. the multiplication with the
! * volume is present to be consistent with the flow residuals; also
!  the negative value is taken, again to be consistent with the
! * flow equations. also multiply by iblank so that no updates occur
!  in holes or the overset boundary.
    use blockpointers
    implicit none
! local variables
    integer(kind=inttype) :: i, j, k, ii
    real(kind=realtype) :: rblank
    intrinsic mod
    intrinsic real
    intrinsic max
    real(realtype) :: x1
    if (associated(scratchd)) scratchd = 0.0_8
!$bwd-of ii-loop 
    do ii=0,nx*ny*nz-1
      i = mod(ii, nx) + 2
      j = mod(ii/nx, ny) + 2
      k = ii/(nx*ny) + 2
      x1 = real(iblank(i, j, k), realtype)
      if (x1 .lt. zero) then
        rblank = zero
      else
        rblank = x1
      end if
      scratchd(i, j, k, idvt) = scratchd(i, j, k, idvt) - volref(i, j, k&
&       )*rblank*dwd(i, j, k, itu1)
      dwd(i, j, k, itu1) = 0.0_8
    end do
  end subroutine saresscale_fast_b

  subroutine saresscale()
!
!  multiply the residual by the volume and store this in dw; this
! * is done for monitoring reasons only. the multiplication with the
! * volume is present to be consistent with the flow residuals; also
!  the negative value is taken, again to be consistent with the
! * flow equations. also multiply by iblank so that no updates occur
!  in holes or the overset boundary.
    use blockpointers
    implicit none
! local variables
    integer(kind=inttype) :: i, j, k, ii
    real(kind=realtype) :: rblank
    intrinsic mod
    intrinsic real
    intrinsic max
    real(realtype) :: x1
!$ad ii-loop
    do ii=0,nx*ny*nz-1
      i = mod(ii, nx) + 2
      j = mod(ii/nx, ny) + 2
      k = ii/(nx*ny) + 2
      x1 = real(iblank(i, j, k), realtype)
      if (x1 .lt. zero) then
        rblank = zero
      else
        rblank = x1
      end if
      dw(i, j, k, itu1) = -(volref(i, j, k)*scratch(i, j, k, idvt)*&
&       rblank)
    end do
  end subroutine saresscale

end module sa_fast_b

