!        generated by tapenade     (inria, ecuador team)
!  tapenade 3.16 (develop) - 22 aug 2023 15:51
!
module sagammaretheta_fast_b
! this module contains the source code related to the sst turbulence
! model. it is slightly more modularized than the original which makes
! performing reverse mode ad simplier.
  use constants, only : realtype
  implicit none
  real(kind=realtype), dimension(:, :, :, :, :), allocatable :: qq

contains
  subroutine sagammaretheta_block(resonly)
    use constants
    use blockpointers, only : il, jl, kl
    use inputtimespectral
    use iteration
    use turbutils_fast_b, only : ssteddyviscosity, turbadvection, &
&   unsteadyturbterm, saeddyviscosity
    use turbbcroutines_fast_b, only : bcturbtreatment, &
&   applyallturbbcthisblock
    implicit none
!
!      subroutine argument.
!
    logical, intent(in) :: resonly
!
!      local variables.
!
    integer(kind=inttype) :: nn, sps
! set the arrays for the boundary condition treatment.
    call bcturbtreatment()
! alloc central jacobian memory
    allocate(qq(2:il, 2:jl, 2:kl, 3, 3))
! source terms
    call source()
! advection term
    nn = itu1 - 1
    call turbadvection(3_inttype, 3_inttype, nn, qq)
    call unsteadyturbterm(3_inttype, 3_inttype, nn, qq)
! viscous terms
    call viscous()
! perform the residual scaling
    call resscale()
! the eddy viscosity and the boundary conditions are only
! applied if an actual update has been computed in sagammarethetasolve.
    if (.not.resonly) then
! solve the transport equations for v, gamma, retheta.
      call sagammarethetasolve(resonly)
! compute the corresponding eddy viscosity.
      call saeddyviscosity(2, il, 2, jl, 2, kl)
! set the halo values for the turbulent variables.
! we are on the finest mesh, so the second layer of halo
! cells must be computed as well.
      call applyallturbbcthisblock(.true.)
    end if
    deallocate(qq)
  end subroutine sagammaretheta_block

  subroutine source()
!
!  source terms.
!  determine the source term and its derivative w.r.t. nutilde
!  for all internal cells of the block.
!  remember that the sa field variable nutilde = w(i,j,k,itu1)
    use blockpointers
    use constants
    use paramturb
    use section
    use inputphysics
    use turbmod, only : dvt, vort, prod, kwcd, f1
    use inputdiscretization, only : approxsa
    use flowvarrefstate
    implicit none
! local parameters
    real(kind=realtype), parameter :: f23=two*third
! local variables.
    integer(kind=inttype) :: i, j, k, nn, ii
    real(kind=realtype) :: fv1, fv2, ft2
    real(kind=realtype) :: ss, sst, nu, dist2inv, chi, chi2, chi3
    real(kind=realtype) :: rr, gg, gg6, termfw, fwsa, term1, term2
    real(kind=realtype) :: cv13, kar2inv, cw36, cb3inv
    real(kind=realtype), parameter :: gammastatic=one
    real(kind=realtype), parameter :: rethetastatic=one
    real(kind=realtype) :: dfv1, dfv2, dft2, drr, dgg, dfw
    real(kind=realtype) :: uux, uuy, uuz, vvx, vvy, vvz, wwx, wwy, wwz
    real(kind=realtype) :: div2, fact, sxx, syy, szz, sxy, sxz, syz
    real(kind=realtype) :: vortx, vorty, vortz
    real(kind=realtype) :: omegax, omegay, omegaz
    real(kind=realtype) :: strainmag2, strainprod, vortprod
    real(kind=realtype), parameter :: xminn=1.e-10_realtype
    intrinsic mod
    intrinsic sqrt
    intrinsic exp
    intrinsic min
    intrinsic max
    real(kind=realtype) :: y1
    real(kind=realtype) :: min1
! set model constants
    cv13 = rsacv1**3
    kar2inv = one/rsak**2
    cw36 = rsacw3**6
    cb3inv = one/rsacb3
! determine the non-dimensional wheel speed of this block.
    omegax = timeref*sections(sectionid)%rotrate(1)
    omegay = timeref*sections(sectionid)%rotrate(2)
    omegaz = timeref*sections(sectionid)%rotrate(3)
! create switches to production term depending on the variable that
! should be used
    if (turbprod .eq. katolaunder) then
      print*, 'katolaunder production term not supported for sa'
      stop
    else
!$ad ii-loop
      do ii=0,nx*ny*nz-1
        i = mod(ii, nx) + 2
        j = mod(ii/nx, ny) + 2
        k = ii/(nx*ny) + 2
! compute the gradient of u in the cell center. use is made
! of the fact that the surrounding normals sum up to zero,
! such that the cell i,j,k does not give a contribution.
! the gradient is scaled by the factor 2*vol.
        uux = w(i+1, j, k, ivx)*si(i, j, k, 1) - w(i-1, j, k, ivx)*si(i-&
&         1, j, k, 1) + w(i, j+1, k, ivx)*sj(i, j, k, 1) - w(i, j-1, k, &
&         ivx)*sj(i, j-1, k, 1) + w(i, j, k+1, ivx)*sk(i, j, k, 1) - w(i&
&         , j, k-1, ivx)*sk(i, j, k-1, 1)
        uuy = w(i+1, j, k, ivx)*si(i, j, k, 2) - w(i-1, j, k, ivx)*si(i-&
&         1, j, k, 2) + w(i, j+1, k, ivx)*sj(i, j, k, 2) - w(i, j-1, k, &
&         ivx)*sj(i, j-1, k, 2) + w(i, j, k+1, ivx)*sk(i, j, k, 2) - w(i&
&         , j, k-1, ivx)*sk(i, j, k-1, 2)
        uuz = w(i+1, j, k, ivx)*si(i, j, k, 3) - w(i-1, j, k, ivx)*si(i-&
&         1, j, k, 3) + w(i, j+1, k, ivx)*sj(i, j, k, 3) - w(i, j-1, k, &
&         ivx)*sj(i, j-1, k, 3) + w(i, j, k+1, ivx)*sk(i, j, k, 3) - w(i&
&         , j, k-1, ivx)*sk(i, j, k-1, 3)
! idem for the gradient of v.
        vvx = w(i+1, j, k, ivy)*si(i, j, k, 1) - w(i-1, j, k, ivy)*si(i-&
&         1, j, k, 1) + w(i, j+1, k, ivy)*sj(i, j, k, 1) - w(i, j-1, k, &
&         ivy)*sj(i, j-1, k, 1) + w(i, j, k+1, ivy)*sk(i, j, k, 1) - w(i&
&         , j, k-1, ivy)*sk(i, j, k-1, 1)
        vvy = w(i+1, j, k, ivy)*si(i, j, k, 2) - w(i-1, j, k, ivy)*si(i-&
&         1, j, k, 2) + w(i, j+1, k, ivy)*sj(i, j, k, 2) - w(i, j-1, k, &
&         ivy)*sj(i, j-1, k, 2) + w(i, j, k+1, ivy)*sk(i, j, k, 2) - w(i&
&         , j, k-1, ivy)*sk(i, j, k-1, 2)
        vvz = w(i+1, j, k, ivy)*si(i, j, k, 3) - w(i-1, j, k, ivy)*si(i-&
&         1, j, k, 3) + w(i, j+1, k, ivy)*sj(i, j, k, 3) - w(i, j-1, k, &
&         ivy)*sj(i, j-1, k, 3) + w(i, j, k+1, ivy)*sk(i, j, k, 3) - w(i&
&         , j, k-1, ivy)*sk(i, j, k-1, 3)
! and for the gradient of w.
        wwx = w(i+1, j, k, ivz)*si(i, j, k, 1) - w(i-1, j, k, ivz)*si(i-&
&         1, j, k, 1) + w(i, j+1, k, ivz)*sj(i, j, k, 1) - w(i, j-1, k, &
&         ivz)*sj(i, j-1, k, 1) + w(i, j, k+1, ivz)*sk(i, j, k, 1) - w(i&
&         , j, k-1, ivz)*sk(i, j, k-1, 1)
        wwy = w(i+1, j, k, ivz)*si(i, j, k, 2) - w(i-1, j, k, ivz)*si(i-&
&         1, j, k, 2) + w(i, j+1, k, ivz)*sj(i, j, k, 2) - w(i, j-1, k, &
&         ivz)*sj(i, j-1, k, 2) + w(i, j, k+1, ivz)*sk(i, j, k, 2) - w(i&
&         , j, k-1, ivz)*sk(i, j, k-1, 2)
        wwz = w(i+1, j, k, ivz)*si(i, j, k, 3) - w(i-1, j, k, ivz)*si(i-&
&         1, j, k, 3) + w(i, j+1, k, ivz)*sj(i, j, k, 3) - w(i, j-1, k, &
&         ivz)*sj(i, j-1, k, 3) + w(i, j, k+1, ivz)*sk(i, j, k, 3) - w(i&
&         , j, k-1, ivz)*sk(i, j, k-1, 3)
! compute the components of the stress tensor.
! the combination of the current scaling of the velocity
! gradients (2*vol) and the definition of the stress tensor,
! leads to the factor 1/(4*vol).
        fact = fourth/vol(i, j, k)
        if (turbprod .eq. strain) then
          sxx = two*fact*uux
          syy = two*fact*vvy
          szz = two*fact*wwz
          sxy = fact*(uuy+vvx)
          sxz = fact*(uuz+wwx)
          syz = fact*(vvz+wwy)
! compute 2/3 * divergence of velocity squared
          div2 = f23*(sxx+syy+szz)**2
! compute strain production term
          strainmag2 = two*(sxy**2+sxz**2+syz**2) + sxx**2 + syy**2 + &
&           szz**2
          strainprod = two*strainmag2 - div2
          ss = sqrt(strainprod)
        else if (turbprod .eq. vorticity) then
! compute the three components of the vorticity vector.
! substract the part coming from the rotating frame.
          vortx = two*fact*(wwy-vvz) - two*omegax
          vorty = two*fact*(uuz-wwx) - two*omegay
          vortz = two*fact*(vvx-uuy) - two*omegaz
! compute the vorticity production term
          vortprod = vortx**2 + vorty**2 + vortz**2
! first take the square root of the production term to
! obtain the correct production term for spalart-allmaras.
! we do this to avoid if statements.
          ss = sqrt(vortprod)
        end if
! compute the laminar kinematic viscosity, the inverse of
! wall distance squared, the ratio chi (ratio of nutilde
! and nu) and the functions fv1 and fv2. the latter corrects
! the production term near a viscous wall.
        nu = rlv(i, j, k)/w(i, j, k, irho)
        dist2inv = one/d2wall(i, j, k)**2
        chi = w(i, j, k, itu1)/nu
        chi2 = chi*chi
        chi3 = chi*chi2
        fv1 = chi3/(chi3+cv13)
        fv2 = one - chi/(one+chi*fv1)
! the function ft2, which is designed to keep a laminar
! solution laminar. when running in fully turbulent mode
! this function should be set to 0.0.
        if (useft2sa) then
          ft2 = rsact3*exp(-(rsact4*chi2))
        else
          ft2 = zero
        end if
! correct the production term to account for the influence
! of the wall.
        sst = ss + w(i, j, k, itu1)*fv2*kar2inv*dist2inv
! add rotation term (userotationsa defined in inputparams.f90)
        if (userotationsa) then
          y1 = sqrt(two*strainmag2)
          if (zero .gt. y1) then
            min1 = y1
          else
            min1 = zero
          end if
          sst = sst + rsacrot*min1
        end if
        if (sst .lt. xminn) then
          sst = xminn
        else
          sst = sst
        end if
! compute the function fw. the argument rr is cut off at 10
! to avoid numerical problems. this is ok, because the
! asymptotical value of fw is then already reached.
        rr = w(i, j, k, itu1)*kar2inv*dist2inv/sst
        if (rr .gt. 10.0_realtype) then
          rr = 10.0_realtype
        else
          rr = rr
        end if
        gg = rr + rsacw2*(rr**6-rr)
        gg6 = gg**6
        termfw = ((one+cw36)/(gg6+cw36))**sixth
        fwsa = gg*termfw
! compute the source term; some terms are saved for the
! linearization. the source term is stored in scratch.
        if (approxsa) then
          term1 = zero
        else
          term1 = rsacb1*(one-ft2)*ss
        end if
        term2 = dist2inv*(kar2inv*rsacb1*((one-ft2)*fv2+ft2)-rsacw1*fwsa&
&         )
        scratch(i, j, k, idvt) = (term1+term2*w(i, j, k, itu1))*w(i, j, &
&         k, itu1)
! placeholder equations for sa-gamma-retheta integration.
! gamma and retheta are kept frozen at static values and
! contribute zero to the source residual for now.
        scratch(i, j, k, idvt+1) = scratch(i, j, k, idvt+1) + zero*(w(i&
&         , j, k, itu2)-gammastatic)
        scratch(i, j, k, idvt+2) = scratch(i, j, k, idvt+2) + zero*(w(i&
&         , j, k, itu3)-rethetastatic)
      end do
    end if
  end subroutine source

  subroutine viscous()
!
!  viscous term for sa variable.
!  determine the viscous contribution to the residual
!  for all internal cells of the block.
    use constants
    use blockpointers
    use paramturb
    implicit none
    integer(kind=inttype) :: i, j, k, ii
! viscosity variables
    real(kind=realtype) :: nu, nu_m, nu_p
    real(kind=realtype) :: nut, nut_m, nut_p
    real(kind=realtype) :: nu_tm, nu_tp
    real(kind=realtype) :: nutilde, nutilde_m, nutilde_p
! sa auxiliary functions
    real(kind=realtype) :: chi, chi3
    real(kind=realtype) :: chi_m, chi3_m
    real(kind=realtype) :: chi_p, chi3_p
    real(kind=realtype) :: fv1, fv1_m, fv1_p
! geometry terms
    real(kind=realtype) :: voli, volmi, volpi
    real(kind=realtype) :: xm, ym, zm
    real(kind=realtype) :: xp, yp, zp
    real(kind=realtype) :: xa, ya, za
    real(kind=realtype) :: ttm, ttp
! diffusion coefficients
    real(kind=realtype) :: num, nup
    real(kind=realtype) :: cdm, cdp
    real(kind=realtype) :: cdm_gamma, cdp_gamma
    real(kind=realtype) :: cdm_rt, cdp_rt
! sa nonlinear correction
    real(kind=realtype) :: cnud, cam, cap
    real(kind=realtype) :: nutm, nutp
! matrix coefficients
    real(kind=realtype) :: c1m, c1p, c10
    real(kind=realtype) :: c2m, c2p, c20
    real(kind=realtype) :: c3m, c3p, c30
    real(kind=realtype) :: b1, c1, d1
    real(kind=realtype) :: b2, c2, d2
    real(kind=realtype) :: b3, c3, d3
! constants
    real(kind=realtype) :: cb3inv, cv13
    intrinsic mod
    intrinsic max
    real(kind=realtype) :: max1
    real(kind=realtype) :: max2
    real(kind=realtype) :: max3
    real(kind=realtype) :: max4
    real(kind=realtype) :: max5
    real(kind=realtype) :: max6
    real(kind=realtype) :: max7
    real(kind=realtype) :: max8
    real(kind=realtype) :: max9
    real(kind=realtype) :: max10
    real(kind=realtype) :: max11
    real(kind=realtype) :: max12
    cb3inv = one/rsacb3
    cv13 = rsacv1**3
!$ad ii-loop
! viscous terms in k-direction.
    do ii=0,nx*ny*nz-1
      i = mod(ii, nx) + 2
      j = mod(ii/nx, ny) + 2
      k = ii/(nx*ny) + 2
!mesh geometry contribution
      voli = one/vol(i, j, k)
      volmi = two/(vol(i, j, k)+vol(i, j, k-1))
      volpi = two/(vol(i, j, k)+vol(i, j, k+1))
      xm = sk(i, j, k-1, 1)*volmi
      ym = sk(i, j, k-1, 2)*volmi
      zm = sk(i, j, k-1, 3)*volmi
      xp = sk(i, j, k, 1)*volpi
      yp = sk(i, j, k, 2)*volpi
      zp = sk(i, j, k, 3)*volpi
      xa = half*(sk(i, j, k, 1)+sk(i, j, k-1, 1))*voli
      ya = half*(sk(i, j, k, 2)+sk(i, j, k-1, 2))*voli
      za = half*(sk(i, j, k, 3)+sk(i, j, k-1, 3))*voli
      ttm = xm*xa + ym*ya + zm*za
      ttp = xp*xa + yp*ya + zp*za
      cnud = -(rsacb2*w(i, j, k, itu1)*cb3inv)
      cam = ttm*cnud
      cap = ttp*cnud
      nutm = half*(w(i, j, k-1, itu1)+w(i, j, k, itu1))
      nutp = half*(w(i, j, k+1, itu1)+w(i, j, k, itu1))
! ----- viscosities in cell (i,j,k)
      nu = rlv(i, j, k)/w(i, j, k, irho)
      nutilde = w(i, j, k, itu1)
      chi = nutilde/nu
      chi3 = chi*chi*chi
      fv1 = chi3/(chi3+cv13)
      nut = nutilde*fv1
! ----- k-1 cell
      nu_m = rlv(i, j, k-1)/w(i, j, k-1, irho)
      nutilde_m = w(i, j, k-1, itu1)
      chi_m = nutilde_m/nu_m
      chi3_m = chi_m*chi_m*chi_m
      fv1_m = chi3_m/(chi3_m+cv13)
      nut_m = nutilde_m*fv1_m
! ----- k+1 cell
      nu_p = rlv(i, j, k+1)/w(i, j, k+1, irho)
      nutilde_p = w(i, j, k+1, itu1)
      chi_p = nutilde_p/nu_p
      chi3_p = chi_p*chi_p*chi_p
      fv1_p = chi3_p/(chi3_p+cv13)
      nut_p = nutilde_p*fv1_p
      num = half*(nu_m+nu)
      nup = half*(nu_p+nu)
      nu_tm = half*(nut_m+nut)
      nu_tp = half*(nut_p+nut)
!sa diffusion contribution
      cdm = (num+(one+rsacb2)*nutm)*ttm*cb3inv
      cdp = (nup+(one+rsacb2)*nutp)*ttp*cb3inv
!gamma diffusion contribution
      cdm_gamma = (num+nu_tm/sigmaf)*ttm
      cdp_gamma = (nup+nu_tp/sigmaf)*ttp
!rethata diffusion contribution
      cdm_rt = sigmatheta*(num+nu_tm)*ttm
      cdp_rt = sigmatheta*(nup+nu_tp)*ttp
      if (cdm + cam .lt. zero) then
        c1m = zero
      else
        c1m = cdm + cam
      end if
      if (cdp + cap .lt. zero) then
        c1p = zero
      else
        c1p = cdp + cap
      end if
      c10 = c1m + c1p
      if (cdm_gamma .lt. zero) then
        c2m = zero
      else
        c2m = cdm_gamma
      end if
      if (cdp_gamma .lt. zero) then
        c2p = zero
      else
        c2p = cdp_gamma
      end if
      c20 = c2m + c2p
      if (cdm_rt .lt. zero) then
        c3m = zero
      else
        c3m = cdm_rt
      end if
      if (cdp_rt .lt. zero) then
        c3p = zero
      else
        c3p = cdp_rt
      end if
      c30 = c3m + c3p
      scratch(i, j, k, idvt) = scratch(i, j, k, idvt) + c1m*w(i, j, k-1&
&       , itu1) - c10*w(i, j, k, itu1) + c1p*w(i, j, k+1, itu1)
      scratch(i, j, k, idvt+1) = scratch(i, j, k, idvt+1) + c2m*w(i, j, &
&       k-1, itu2) - c20*w(i, j, k, itu2) + c2p*w(i, j, k+1, itu2)
      scratch(i, j, k, idvt+2) = scratch(i, j, k, idvt+2) + c3m*w(i, j, &
&       k-1, itu3) - c30*w(i, j, k, itu3) + c3p*w(i, j, k+1, itu3)
    end do
!$ad ii-loop
! viscous terms in j-direction.
    do ii=0,nx*ny*nz-1
      i = mod(ii, nx) + 2
      j = mod(ii/nx, ny) + 2
      k = ii/(nx*ny) + 2
      voli = one/vol(i, j, k)
      volmi = two/(vol(i, j, k)+vol(i, j-1, k))
      volpi = two/(vol(i, j, k)+vol(i, j+1, k))
      xm = sj(i, j-1, k, 1)*volmi
      ym = sj(i, j-1, k, 2)*volmi
      zm = sj(i, j-1, k, 3)*volmi
      xp = sj(i, j, k, 1)*volpi
      yp = sj(i, j, k, 2)*volpi
      zp = sj(i, j, k, 3)*volpi
      xa = half*(sj(i, j, k, 1)+sj(i, j-1, k, 1))*voli
      ya = half*(sj(i, j, k, 2)+sj(i, j-1, k, 2))*voli
      za = half*(sj(i, j, k, 3)+sj(i, j-1, k, 3))*voli
      ttm = xm*xa + ym*ya + zm*za
      ttp = xp*xa + yp*ya + zp*za
      cnud = -(rsacb2*w(i, j, k, itu1)*cb3inv)
      cam = ttm*cnud
      cap = ttp*cnud
      nutm = half*(w(i, j-1, k, itu1)+w(i, j, k, itu1))
      nutp = half*(w(i, j+1, k, itu1)+w(i, j, k, itu1))
! ----- viscosities in cell (i,j,k)
      nu = rlv(i, j, k)/w(i, j, k, irho)
      nutilde = w(i, j, k, itu1)
      chi = nutilde/nu
      chi3 = chi*chi*chi
      fv1 = chi3/(chi3+cv13)
      nut = nutilde*fv1
! ----- j-1 cell
      nu_m = rlv(i, j-1, k)/w(i, j-1, k, irho)
      nutilde_m = w(i, j-1, k, itu1)
      chi_m = nutilde_m/nu_m
      chi3_m = chi_m*chi_m*chi_m
      fv1_m = chi3_m/(chi3_m+cv13)
      nut_m = nutilde_m*fv1_m
! ----- j+1 cell
      nu_p = rlv(i, j+1, k)/w(i, j+1, k, irho)
      nutilde_p = w(i, j+1, k, itu1)
      chi_p = nutilde_p/nu_p
      chi3_p = chi_p*chi_p*chi_p
      fv1_p = chi3_p/(chi3_p+cv13)
      nut_p = nutilde_p*fv1_p
      num = half*(nu_m+nu)
      nup = half*(nu_p+nu)
      nu_tm = half*(nut_m+nut)
      nu_tp = half*(nut_p+nut)
!sa diffusion contribution
      cdm = (num+(one+rsacb2)*nutm)*ttm*cb3inv
      cdp = (nup+(one+rsacb2)*nutp)*ttp*cb3inv
!gamma diffusion contribution
      cdm_gamma = (num+nu_tm/sigmaf)*ttm
      cdp_gamma = (nup+nu_tp/sigmaf)*ttp
!rethata diffusion contribution
      cdm_rt = sigmatheta*(num+nu_tm)*ttm
      cdp_rt = sigmatheta*(nup+nu_tp)*ttp
      if (cdm + cam .lt. zero) then
        c1m = zero
      else
        c1m = cdm + cam
      end if
      if (cdp + cap .lt. zero) then
        c1p = zero
      else
        c1p = cdp + cap
      end if
      c10 = c1m + c1p
      if (cdm_gamma .lt. zero) then
        c2m = zero
      else
        c2m = cdm_gamma
      end if
      if (cdp_gamma .lt. zero) then
        c2p = zero
      else
        c2p = cdp_gamma
      end if
      c20 = c2m + c2p
      if (cdm_rt .lt. zero) then
        c3m = zero
      else
        c3m = cdm_rt
      end if
      if (cdp_rt .lt. zero) then
        c3p = zero
      else
        c3p = cdp_rt
      end if
      c30 = c3m + c3p
      scratch(i, j, k, idvt) = scratch(i, j, k, idvt) + c1m*w(i, j-1, k&
&       , itu1) - c10*w(i, j, k, itu1) + c1p*w(i, j+1, k, itu1)
      scratch(i, j, k, idvt+1) = scratch(i, j, k, idvt+1) + c2m*w(i, j-1&
&       , k, itu2) - c20*w(i, j, k, itu2) + c2p*w(i, j+1, k, itu2)
      scratch(i, j, k, idvt+2) = scratch(i, j, k, idvt+2) + c3m*w(i, j-1&
&       , k, itu3) - c30*w(i, j, k, itu3) + c3p*w(i, j+1, k, itu3)
      b1 = -c1m
      c1 = c10
      d1 = -c1p
! update the central jacobian. for nonboundary cells this
! is simply c1. for boundary cells this is slightly more
! complicated, because the boundary conditions are treated
! implicitly and the off-diagonal terms b1 and d1 must be
! taken into account.
! the boundary conditions are only treated implicitly if
! the diagonal dominance of the matrix is increased.
      if (j .eq. 2) then
        if (bmtj1(i, j, itu1, itu1) .lt. zero) then
          max1 = zero
        else
          max1 = bmtj1(i, j, itu1, itu1)
        end if
        qq(i, j, k, 1, 1) = qq(i, j, k, 1, 1) + c1 - b1*max1
      else if (j .eq. jl) then
        if (bmtj2(i, j, itu1, itu1) .lt. zero) then
          max2 = zero
        else
          max2 = bmtj2(i, j, itu1, itu1)
        end if
        qq(i, j, k, 1, 1) = qq(i, j, k, 1, 1) + c1 - d1*max2
      else
        qq(i, j, k, 1, 1) = qq(i, j, k, 1, 1) + c1
      end if
!====================================================
! gamma equation
!====================================================
      b2 = -c2m
      c2 = c20
      d2 = -c2p
      if (j .eq. 2) then
        if (bmtj1(i, j, itu2, itu2) .lt. zero) then
          max3 = zero
        else
          max3 = bmtj1(i, j, itu2, itu2)
        end if
        qq(i, j, k, 2, 2) = qq(i, j, k, 2, 2) + c2 - b2*max3
      else if (j .eq. jl) then
        if (bmtj2(i, j, itu2, itu2) .lt. zero) then
          max4 = zero
        else
          max4 = bmtj2(i, j, itu2, itu2)
        end if
        qq(i, j, k, 2, 2) = qq(i, j, k, 2, 2) + c2 - d2*max4
      else
        qq(i, j, k, 2, 2) = qq(i, j, k, 2, 2) + c2
      end if
!====================================================
! retheta equation
!====================================================
      b3 = -c3m
      c3 = c30
      d3 = -c3p
      if (j .eq. 2) then
        if (bmtj1(i, j, itu3, itu3) .lt. zero) then
          max5 = zero
        else
          max5 = bmtj1(i, j, itu3, itu3)
        end if
        qq(i, j, k, 3, 3) = qq(i, j, k, 3, 3) + c3 - b3*max5
      else if (j .eq. jl) then
        if (bmtj2(i, j, itu3, itu3) .lt. zero) then
          max6 = zero
        else
          max6 = bmtj2(i, j, itu3, itu3)
        end if
        qq(i, j, k, 3, 3) = qq(i, j, k, 3, 3) + c3 - d3*max6
      else
        qq(i, j, k, 3, 3) = qq(i, j, k, 3, 3) + c3
      end if
    end do
!$ad ii-loop
! viscous terms in i-direction.
    do ii=0,nx*ny*nz-1
      i = mod(ii, nx) + 2
      j = mod(ii/nx, ny) + 2
      k = ii/(nx*ny) + 2
      voli = one/vol(i, j, k)
      volmi = two/(vol(i, j, k)+vol(i-1, j, k))
      volpi = two/(vol(i, j, k)+vol(i+1, j, k))
      xm = si(i-1, j, k, 1)*volmi
      ym = si(i-1, j, k, 2)*volmi
      zm = si(i-1, j, k, 3)*volmi
      xp = si(i, j, k, 1)*volpi
      yp = si(i, j, k, 2)*volpi
      zp = si(i, j, k, 3)*volpi
      xa = half*(si(i, j, k, 1)+si(i-1, j, k, 1))*voli
      ya = half*(si(i, j, k, 2)+si(i-1, j, k, 2))*voli
      za = half*(si(i, j, k, 3)+si(i-1, j, k, 3))*voli
      ttm = xm*xa + ym*ya + zm*za
      ttp = xp*xa + yp*ya + zp*za
      cnud = -(rsacb2*w(i, j, k, itu1)*cb3inv)
      cam = ttm*cnud
      cap = ttp*cnud
      nutm = half*(w(i-1, j, k, itu1)+w(i, j, k, itu1))
      nutp = half*(w(i+1, j, k, itu1)+w(i, j, k, itu1))
! ----- viscosities in cell (i,j,k)
      nu = rlv(i, j, k)/w(i, j, k, irho)
      nutilde = w(i, j, k, itu1)
      chi = nutilde/nu
      chi3 = chi*chi*chi
      fv1 = chi3/(chi3+cv13)
      nut = nutilde*fv1
! ----- i-1 cell
      nu_m = rlv(i-1, j, k)/w(i-1, j, k, irho)
      nutilde_m = w(i-1, j, k, itu1)
      chi_m = nutilde_m/nu_m
      chi3_m = chi_m*chi_m*chi_m
      fv1_m = chi3_m/(chi3_m+cv13)
      nut_m = nutilde_m*fv1_m
! ----- i+1 cell
      nu_p = rlv(i+1, j, k)/w(i+1, j, k, irho)
      nutilde_p = w(i+1, j, k, itu1)
      chi_p = nutilde_p/nu_p
      chi3_p = chi_p*chi_p*chi_p
      fv1_p = chi3_p/(chi3_p+cv13)
      nut_p = nutilde_p*fv1_p
      num = half*(nu_m+nu)
      nup = half*(nu_p+nu)
      nu_tm = half*(nut_m+nut)
      nu_tp = half*(nut_p+nut)
!sa diffusion contribution
      cdm = (num+(one+rsacb2)*nutm)*ttm*cb3inv
      cdp = (nup+(one+rsacb2)*nutp)*ttp*cb3inv
!gamma diffusion contribution
      cdm_gamma = (num+nu_tm/sigmaf)*ttm
      cdp_gamma = (nup+nu_tp/sigmaf)*ttp
!rethata diffusion contribution
      cdm_rt = sigmatheta*(num+nu_tm)*ttm
      cdp_rt = sigmatheta*(nup+nu_tp)*ttp
      if (cdm + cam .lt. zero) then
        c1m = zero
      else
        c1m = cdm + cam
      end if
      if (cdp + cap .lt. zero) then
        c1p = zero
      else
        c1p = cdp + cap
      end if
      c10 = c1m + c1p
      if (cdm_gamma .lt. zero) then
        c2m = zero
      else
        c2m = cdm_gamma
      end if
      if (cdp_gamma .lt. zero) then
        c2p = zero
      else
        c2p = cdp_gamma
      end if
      c20 = c2m + c2p
      if (cdm_rt .lt. zero) then
        c3m = zero
      else
        c3m = cdm_rt
      end if
      if (cdp_rt .lt. zero) then
        c3p = zero
      else
        c3p = cdp_rt
      end if
      c30 = c3m + c3p
      scratch(i, j, k, idvt) = scratch(i, j, k, idvt) + c1m*w(i-1, j, k&
&       , itu1) - c10*w(i, j, k, itu1) + c1p*w(i+1, j, k, itu1)
      scratch(i, j, k, idvt+1) = scratch(i, j, k, idvt+1) + c2m*w(i-1, j&
&       , k, itu2) - c20*w(i, j, k, itu2) + c2p*w(i+1, j, k, itu2)
      scratch(i, j, k, idvt+2) = scratch(i, j, k, idvt+2) + c3m*w(i-1, j&
&       , k, itu3) - c30*w(i, j, k, itu3) + c3p*w(i+1, j, k, itu3)
      b1 = -c1m
      c1 = c10
      d1 = -c1p
! update the central jacobian. for nonboundary cells this
! is simply c1. for boundary cells this is slightly more
! complicated, because the boundary conditions are treated
! implicitly and the off-diagonal terms b1 and d1 must be
! taken into account.
! the boundary conditions are only treated implicitly if
! the diagonal dominance of the matrix is increased.
      if (i .eq. 2) then
        if (bmti1(i, j, itu1, itu1) .lt. zero) then
          max7 = zero
        else
          max7 = bmti1(i, j, itu1, itu1)
        end if
        qq(i, j, k, 1, 1) = qq(i, j, k, 1, 1) + c1 - b1*max7
      else if (i .eq. il) then
        if (bmti2(i, j, itu1, itu1) .lt. zero) then
          max8 = zero
        else
          max8 = bmti2(i, j, itu1, itu1)
        end if
        qq(i, j, k, 1, 1) = qq(i, j, k, 1, 1) + c1 - d1*max8
      else
        qq(i, j, k, 1, 1) = qq(i, j, k, 1, 1) + c1
      end if
!====================================================
! gamma equation
!====================================================
      b2 = -c2m
      c2 = c20
      d2 = -c2p
      if (i .eq. 2) then
        if (bmti1(i, j, itu2, itu2) .lt. zero) then
          max9 = zero
        else
          max9 = bmti1(i, j, itu2, itu2)
        end if
        qq(i, j, k, 2, 2) = qq(i, j, k, 2, 2) + c2 - b2*max9
      else if (i .eq. il) then
        if (bmti2(i, j, itu2, itu2) .lt. zero) then
          max10 = zero
        else
          max10 = bmti2(i, j, itu2, itu2)
        end if
        qq(i, j, k, 2, 2) = qq(i, j, k, 2, 2) + c2 - d2*max10
      else
        qq(i, j, k, 2, 2) = qq(i, j, k, 2, 2) + c2
      end if
!====================================================
! retheta equation
!====================================================
      b3 = -c3m
      c3 = c30
      d3 = -c3p
      if (i .eq. 2) then
        if (bmti1(i, j, itu3, itu3) .lt. zero) then
          max11 = zero
        else
          max11 = bmti1(i, j, itu3, itu3)
        end if
        qq(i, j, k, 3, 3) = qq(i, j, k, 3, 3) + c3 - b3*max11
      else if (i .eq. il) then
        if (bmti2(i, j, itu3, itu3) .lt. zero) then
          max12 = zero
        else
          max12 = bmti2(i, j, itu3, itu3)
        end if
        qq(i, j, k, 3, 3) = qq(i, j, k, 3, 3) + c3 - d3*max12
      else
        qq(i, j, k, 3, 3) = qq(i, j, k, 3, 3) + c3
      end if
    end do
  end subroutine viscous

  subroutine resscale()
!
!  multiply the residual by the volume and store this in dw; this
! * is done for monitoring reasons only. the multiplication with the
! * volume is present to be consistent with the flow residuals; also
!  the negative value is taken, again to be consistent with the
! * flow equations. also multiply by iblank so that no updates occur
!  in holes or the overset boundary.
    use constants
    use blockpointers
    implicit none
! local variables
    integer(kind=inttype) :: i, j, k, ii
    real(kind=realtype) :: rblank
    intrinsic mod
    intrinsic real
    intrinsic max
    real(realtype) :: x1
!$ad ii-loop
    do ii=0,nx*ny*nz-1
      i = mod(ii, nx) + 2
      j = mod(ii/nx, ny) + 2
      k = ii/(nx*ny) + 2
      x1 = real(iblank(i, j, k), realtype)
      if (x1 .lt. zero) then
        rblank = zero
      else
        rblank = x1
      end if
! sa variable ν~
      dw(i, j, k, itu1) = -(volref(i, j, k)*scratch(i, j, k, idvt)*&
&       rblank)
! gamma
      dw(i, j, k, itu2) = -(volref(i, j, k)*scratch(i, j, k, idvt+1)*&
&       rblank)
! retheta_t
      dw(i, j, k, itu3) = -(volref(i, j, k)*scratch(i, j, k, idvt+2)*&
&       rblank)
    end do
  end subroutine resscale

  subroutine sagammarethetasolve(resonly)
!
!       residual-first sa-gamma-retheta transport solve.
!       the residual (source + advection + unsteady + viscous)
!       is assembled for 3 equations and updates are applied
!       explicitly without the sst adi solver path.
!
    use blockpointers
    use constants
    use flowvarrefstate
    use inputiteration
    use inputphysics
    use paramturb
    implicit none
!
!      subroutine arguments.
!
    logical, intent(in) :: resonly
!
!      local variables.
!
    integer(kind=inttype) :: i, j, k, nn
    real(kind=realtype) :: rblank, factor
    real(kind=realtype), dimension(:, :, :, :), pointer :: dvt
    intrinsic real
    intrinsic max
    intrinsic min
    real(kind=realtype) :: y1
! set a couple of pointers to the correct entries in dw to
! make the code more readable.
    dvt => scratch(1:, 1:, 1:, idvt:)
    if (resonly) then
      return
    else
! explicit update only; implicit adi solver path intentionally removed.
      factor = one
      if (turbrelax .eq. turbrelaxexplicit) factor = alfaturb
      do k=2,kl
        do j=2,jl
          do i=2,il
            rblank = real(iblank(i, j, k), realtype)
            w(i, j, k, itu1) = w(i, j, k, itu1) + factor*dvt(i, j, k, 1)&
&             *rblank
            if (w(i, j, k, itu1) .lt. zero) then
              w(i, j, k, itu1) = zero
            else
              w(i, j, k, itu1) = w(i, j, k, itu1)
            end if
            w(i, j, k, itu2) = w(i, j, k, itu2) + factor*dvt(i, j, k, 2)&
&             *rblank
            if (one .gt. w(i, j, k, itu2)) then
              y1 = w(i, j, k, itu2)
            else
              y1 = one
            end if
            if (zero .lt. y1) then
              w(i, j, k, itu2) = y1
            else
              w(i, j, k, itu2) = zero
            end if
            w(i, j, k, itu3) = w(i, j, k, itu3) + factor*dvt(i, j, k, 3)&
&             *rblank
            if (w(i, j, k, itu3) .lt. 1.e-5_realtype*winf(itu3)) then
              w(i, j, k, itu3) = 1.e-5_realtype*winf(itu3)
            else
              w(i, j, k, itu3) = w(i, j, k, itu3)
            end if
          end do
        end do
      end do
    end if
  end subroutine sagammarethetasolve

! Stub fast reverse-mode AD of Source (saGammaRetheta)
! Regenerate with: make -f Makefile_tapenade ad_reverse_fast
  subroutine source_fast_b()
    implicit none
    ! Placeholder: regenerate with Tapenade ad_reverse_fast
  end subroutine source_fast_b

! Stub fast reverse-mode AD of Viscous (saGammaRetheta)
  subroutine viscous_fast_b()
    implicit none
    ! Placeholder: regenerate with Tapenade ad_reverse_fast
  end subroutine viscous_fast_b

! Stub fast reverse-mode AD of ResScale (saGammaRetheta)
  subroutine resscale_fast_b()
    implicit none
    ! Placeholder: regenerate with Tapenade ad_reverse_fast
  end subroutine resscale_fast_b

end module sagammaretheta_fast_b

